CHECKSUM: "3353607666 3685979931"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_axi_sub_wrap.u_axi_sub
ANNOTATION: "VC_COV_UNR"
Block 80 "2670426016" "axi_w_state_din = S_SERR;"
ANNOTATION: "VC_COV_UNR"
Block 129 "970532631" "chk_r_state_din = S_RESP;"
ANNOTATION: "VC_COV_UNR"
Block 171 "1434127636" "chk_w_state_din = S_RESP;"
ANNOTATION: "VC_COV_UNR"
Block 183 "1714330419" "chk_w_dw_cplt_din = (chk_w_dw_cplt_q || chk_w_engn_write);"
CHECKSUM: "3055974457 3912678340"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_crypto_wrap
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 unused_ob_overflow_err "logic unused_ob_overflow_err"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 unused_ob_overflow_err "logic unused_ob_overflow_err"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 unused_ob_underflow_err "logic unused_ob_underflow_err"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 unused_ob_underflow_err "logic unused_ob_underflow_err"
CHECKSUM: "3284043580 4019309916"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_axi_sub_wrap
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sinc_axi_sub_bresp [0] "logic sinc_axi_sub_bresp[1:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 csr_addr [0] "logic csr_addr[9:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 csr_addr [1] "logic csr_addr[9:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [0] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [1] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [10] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [11] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [13] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [14] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [15] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [16] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [20] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [21] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [22] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [23] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [28] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [29] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sub_engn_addr_o [30] "logic sub_engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 unused_sub_engn_user_o [8] "logic unused_sub_engn_user_o[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 unused_sub_engn_user_o [9] "logic unused_sub_engn_user_o[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 unused_sub_engn_user_o [10] "logic unused_sub_engn_user_o[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 unused_sub_engn_user_o [11] "logic unused_sub_engn_user_o[11:0]"
CHECKSUM: "2050619287 311475779"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_crypto_wrap.u_crypto_wrap_ctrl
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 aes_ctrl_state [6] "logic aes_ctrl_state[6:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 next_aes_ctrl_state [6] "logic next_aes_ctrl_state[6:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 next_aes_ctrl_state [6] "logic next_aes_ctrl_state[6:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 aes_ctrl_sub_state [5] "logic aes_ctrl_sub_state[5:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [0] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [0] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [1] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [1] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [2] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [2] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [3] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [3] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [4] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [4] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [5] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [5] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [6] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [6] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [24] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [24] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [25] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [25] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [26] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [26] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [27] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [27] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [28] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [28] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [29] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [29] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [30] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [30] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 key_addr [31] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 key_addr [31] "logic key_addr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 rdata_bt_cnt [7] "logic rdata_bt_cnt[7:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 wdata_bt_cnt [7] "logic wdata_bt_cnt[7:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 aes_block_cnt [5] "logic aes_block_cnt[5:0]"
CHECKSUM: "3019501273 1893824282"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_reg_ctrl
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 csr_addr [0] "logic csr_addr[9:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 csr_addr [1] "logic csr_addr[9:0]"
CHECKSUM: "3666800856 3189680496"
INSTANCE: hdl_top.sinc.u_sinc_cmu
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sinc_axi_mgr_araddr [0] "logic sinc_axi_mgr_araddr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sinc_axi_mgr_araddr [1] "logic sinc_axi_mgr_araddr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sinc_axi_mgr_awaddr [0] "logic sinc_axi_mgr_awaddr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sinc_axi_mgr_awaddr [1] "logic sinc_axi_mgr_awaddr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sinc_axi_sub_bresp [0] "logic sinc_axi_sub_bresp[1:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 mgr_engn_cwlen_i [3] "logic mgr_engn_cwlen_i[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 mgr_engn_cwlen_i [5] "logic mgr_engn_cwlen_i[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 csr_addr [0] "logic csr_addr[9:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 csr_addr [1] "logic csr_addr[9:0]"
CHECKSUM: "721819789 67991534"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_dma
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 mgr_engn_cwlen_i [3] "logic mgr_engn_cwlen_i[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 mgr_engn_cwlen_i [5] "logic mgr_engn_cwlen_i[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 dma_w_len_q [1] "logic dma_w_len_q[7:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 dma_w_len_q [3] "logic dma_w_len_q[7:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 dma_r_last_beat [0] "logic dma_r_last_beat[7:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 dma_w_last_beat [0] "logic dma_w_last_beat[7:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 dma_w_last_beat [1] "logic dma_w_last_beat[7:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 dma_w_len_mux [1] "logic dma_w_len_mux[29:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 dma_w_len_mux [3] "logic dma_w_len_mux[29:0]"
CHECKSUM: "3353607666 3586516139"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_axi_sub_wrap.u_axi_sub
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 bresp_o [0] "net bresp_o[1:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [0] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [1] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [10] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [11] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [13] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [14] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [15] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [16] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [20] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [21] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [22] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [23] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [28] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [29] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_addr_o [30] "net engn_addr_o[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_user_o [8] "net engn_user_o[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_user_o [9] "net engn_user_o[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_user_o [10] "net engn_user_o[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 engn_user_o [11] "net engn_user_o[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 cr_start_axi_q [0] "reg cr_start_axi_q[0:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 cr_start_chk_q [0] "reg cr_start_chk_q[0:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 cr_end_q [0] "reg cr_end_q[0:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 cw_start_axi_q [0] "reg cw_start_axi_q[0:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 cw_start_chk_q [0] "reg cw_start_chk_q[0:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 cw_end_q [0] "reg cw_end_q[0:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 dr_start_q [0] "reg dr_start_q[0:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 dr_end_q [0] "reg dr_end_q[0:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 dw_start_q [0] "reg dw_start_q[0:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 dw_end_q [0] "reg dw_end_q[0:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 axi_w_state_q [1] "reg axi_w_state_q[1:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 axi_w_state_din [1] "reg axi_w_state_din[1:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 axi_w_state_din [1] "reg axi_w_state_din[1:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 axi_b_resp_q [0] "reg axi_b_resp_q[1:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_din [32] "reg chk_r_addr_din[32:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_din [32] "reg chk_r_addr_din[32:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [8] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [8] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [9] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [9] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [10] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [10] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [11] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [11] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [12] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [12] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [13] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [13] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [14] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [14] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [15] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [15] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [16] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [16] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [17] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [17] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [18] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [18] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [19] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [19] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [20] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [20] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [21] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [21] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [22] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [22] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [23] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [23] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [24] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [24] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [25] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [25] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [26] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [26] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [27] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [27] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [28] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [28] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [29] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [29] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [30] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [30] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv [31] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv [31] "net chk_r_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [8] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [8] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [9] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [9] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [10] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [10] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [11] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [11] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [12] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [12] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [13] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [13] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [14] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [14] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [15] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [15] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [16] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [16] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [17] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [17] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [18] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [18] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [19] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [19] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [20] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [20] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [21] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [21] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [22] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [22] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [23] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [23] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [24] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [24] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [25] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [25] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [26] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [26] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [27] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [27] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [28] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [28] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [29] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [29] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [30] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [30] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [31] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [31] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [32] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [32] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [33] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [33] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [34] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [34] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [35] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [35] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [36] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [36] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [37] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [37] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_r_addr_adv_shft [38] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_r_addr_adv_shft [38] "net chk_r_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_r_busy "net chk_a_r_busy"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_r_busy "net chk_a_r_busy"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_w_busy "net chk_a_w_busy"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_w_busy "net chk_a_w_busy"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_din [32] "reg chk_w_addr_din[32:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_din [32] "reg chk_w_addr_din[32:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [8] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [8] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [9] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [9] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [10] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [10] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [11] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [11] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [12] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [12] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [13] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [13] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [14] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [14] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [15] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [15] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [16] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [16] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [17] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [17] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [18] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [18] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [19] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [19] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [20] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [20] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [21] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [21] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [22] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [22] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [23] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [23] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [24] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [24] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [25] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [25] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [26] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [26] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [27] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [27] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [28] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [28] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [29] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [29] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [30] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [30] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv [31] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv [31] "net chk_w_addr_adv[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [8] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [8] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [9] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [9] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [10] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [10] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [11] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [11] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [12] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [12] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [13] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [13] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [14] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [14] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [15] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [15] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [16] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [16] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [17] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [17] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [18] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [18] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [19] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [19] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [20] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [20] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [21] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [21] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [22] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [22] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [23] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [23] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [24] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [24] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [25] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [25] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [26] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [26] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [27] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [27] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [28] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [28] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [29] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [29] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [30] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [30] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [31] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [31] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [32] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [32] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [33] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [33] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [34] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [34] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [35] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [35] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [36] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [36] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [37] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [37] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_w_addr_adv_shft [38] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_w_addr_adv_shft [38] "net chk_w_addr_adv_shft[38:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [0] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [0] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [1] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [1] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [10] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [10] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [11] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [11] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [13] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [13] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [14] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [14] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [15] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [15] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [16] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [16] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [20] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [20] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [21] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [21] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [22] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [22] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [23] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [23] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [28] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [28] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [29] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [29] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_din [30] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_addr_din [30] "net chk_a_engn_addr_din[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [0] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [1] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [10] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [11] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [13] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [14] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [15] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [16] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [20] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [21] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [22] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [23] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [28] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [29] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_addr_q [30] "reg chk_a_engn_addr_q[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_user_din [8] "net chk_a_engn_user_din[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_user_din [8] "net chk_a_engn_user_din[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_user_din [9] "net chk_a_engn_user_din[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_user_din [9] "net chk_a_engn_user_din[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_user_din [10] "net chk_a_engn_user_din[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_user_din [10] "net chk_a_engn_user_din[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_user_din [11] "net chk_a_engn_user_din[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 1to0 chk_a_engn_user_din [11] "net chk_a_engn_user_din[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_user_q [8] "reg chk_a_engn_user_q[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_user_q [9] "reg chk_a_engn_user_q[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_user_q [10] "reg chk_a_engn_user_q[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 chk_a_engn_user_q [11] "reg chk_a_engn_user_q[11:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 dw_fifo_q [0][36] "reg [36:0]dw_fifo_q[0:0]"
CHECKSUM: "1432683219 3019469556"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_crypto_wrap.u_crypto_wrap_ctrl.u_sinc_cmu_crypto_wrap_ctrl_ret
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 rdata_bt_cnt [7] "logic rdata_bt_cnt[7:0]"
CHECKSUM: "4257887522 1616668096"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_reg_ctrl.u_sinc_regs
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 csr_addr [0] "net csr_addr[9:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 csr_addr [1] "net csr_addr[9:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 csr_internal_bus_address [0] "net csr_internal_bus_address[9:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 csr_internal_bus_address [1] "net csr_internal_bus_address[9:0]"
CHECKSUM: "3353607666 604360930"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_axi_sub_wrap.u_axi_sub
ANNOTATION: "VC_COV_UNR"
Condition 56 "1796851434" "(chk_r_en && chk_a_invalid_r && chk_r_rdy_i) 1 -1" (1 "011")
ANNOTATION: "VC_COV_UNR"
Condition 58 "3870792749" "(chk_r_en && chk_a_valid_r) 1 -1" (1 "01")
ANNOTATION: "VC_COV_UNR"
Condition 58 "3870792749" "(chk_r_en && chk_a_valid_r) 1 -1" (2 "10")
ANNOTATION: "VC_COV_UNR"
Condition 59 "3398993303" "(chk_r_rdy_i && ((~chk_a_r_busy)) && ((~chk_a_w_busy))) 1 -1" (2 "101")
ANNOTATION: "VC_COV_UNR"
Condition 59 "3398993303" "(chk_r_rdy_i && ((~chk_a_r_busy)) && ((~chk_a_w_busy))) 1 -1" (3 "110")
ANNOTATION: "VC_COV_UNR"
Condition 63 "900254491" "((chk_r_addr_adv == 32'h00000002) ? (({chk_r_addr_q[31:1], 1'b0} + chk_r_addr_adv)) : ((chk_r_addr_q + chk_r_addr_adv))) 1 -1" (2 "1")
ANNOTATION: "VC_COV_UNR"
Condition 64 "1887619749" "(chk_r_addr_adv == 32'h00000002) 1 -1" (2 "1")
ANNOTATION: "VC_COV_UNR"
Condition 77 "3625594136" "(chk_w_en && chk_a_invalid_w && chk_w_rdy_i) 1 -1" (1 "011")
ANNOTATION: "VC_COV_UNR"
Condition 78 "1265664018" "(chk_w_en && chk_w_perr) 1 -1" (1 "01")
ANNOTATION: "VC_COV_UNR"
Condition 81 "2307086808" "(chk_w_en && chk_a_valid_w) 1 -1" (1 "01")
ANNOTATION: "VC_COV_UNR"
Condition 81 "2307086808" "(chk_w_en && chk_a_valid_w) 1 -1" (2 "10")
ANNOTATION: "VC_COV_UNR"
Condition 82 "2669990175" "(chk_w_rdy_i && ((~chk_a_r_busy)) && ((~chk_a_w_busy))) 1 -1" (2 "101")
ANNOTATION: "VC_COV_UNR"
Condition 82 "2669990175" "(chk_w_rdy_i && ((~chk_a_r_busy)) && ((~chk_a_w_busy))) 1 -1" (3 "110")
ANNOTATION: "VC_COV_UNR"
Condition 84 "5797735" "((chk_w_addr_adv == 32'h00000004) ? (({chk_w_addr_q[31:2], 2'b0} + chk_w_addr_adv)) : ((chk_w_addr_adv == 32'h00000002) ? (({chk_w_addr_q[31:1], 1'b0} + chk_w_addr_adv)) : ((chk_w_addr_q + chk_w_addr_adv)))) 1 -1" (1 "0")
ANNOTATION: "VC_COV_UNR"
Condition 85 "3359307208" "(chk_w_addr_adv == 32'h00000004) 1 -1" (1 "0")
ANNOTATION: "VC_COV_UNR"
Condition 86 "714185592" "((chk_w_addr_adv == 32'h00000002) ? (({chk_w_addr_q[31:1], 1'b0} + chk_w_addr_adv)) : ((chk_w_addr_q + chk_w_addr_adv))) 1 -1" (1 "0")
ANNOTATION: "VC_COV_UNR"
Condition 86 "714185592" "((chk_w_addr_adv == 32'h00000002) ? (({chk_w_addr_q[31:1], 1'b0} + chk_w_addr_adv)) : ((chk_w_addr_q + chk_w_addr_adv))) 1 -1" (2 "1")
ANNOTATION: "VC_COV_UNR"
Condition 87 "2639719541" "(chk_w_addr_adv == 32'h00000002) 1 -1" (2 "1")
ANNOTATION: "VC_COV_UNR"
Condition 93 "618138857" "(engn_wen_o && ((!engn_w_rdy_i))) 1 -1" (3 "11")
ANNOTATION: "VC_COV_UNR"
Condition 94 "3193975663" "(chk_w_dw_cplt_q || chk_w_engn_write) 1 -1" (1 "00")
ANNOTATION: "VC_COV_UNR"
Condition 94 "3193975663" "(chk_w_dw_cplt_q || chk_w_engn_write) 1 -1" (2 "01")
ANNOTATION: "VC_COV_UNR"
Condition 94 "3193975663" "(chk_w_dw_cplt_q || chk_w_engn_write) 1 -1" (3 "10")
ANNOTATION: "VC_COV_UNR"
Condition 128 "3456955521" "((cw_start_axi_advance && cw_end_advance) ? cw_remaining_axi_q : (cw_start_axi_advance ? ((cw_remaining_axi_q + CFDP1W_ONE)) : (cw_end_advance ? ((cw_remaining_axi_q - CFDP1W_ONE)) : cw_remaining_axi_q))) 1 -1" (2 "1")
ANNOTATION: "VC_COV_UNR"
Condition 129 "948671939" "(cw_start_axi_advance && cw_end_advance) 1 -1" (3 "11")
ANNOTATION: "VC_COV_UNR"
Condition 200 "2980812754" "(axi_r_chk_err_q && ( ! (engn_ren_o && ((!engn_r_rdy_i))) )) 1 -1" (2 "10")
ANNOTATION: "VC_COV_UNR"
Condition 201 "1010690501" "( ! (engn_ren_o && ((!engn_r_rdy_i))) ) 1 -1" (2 "1")
ANNOTATION: "VC_COV_UNR"
Condition 202 "1917158900" "(engn_ren_o && ((!engn_r_rdy_i))) 1 -1" (3 "11")
ANNOTATION: "VC_COV_UNR"
Condition 217 "2198596062" "(((~chk_a_engn_ren_q)) || (dr_entries_q != (DFD - 1))) 1 -1" (2 "01")
ANNOTATION: "VC_COV_UNR"
Condition 218 "100249969" "(dr_entries_q != (DFD - 1)) 1 -1" (2 "1")
ANNOTATION: "VC_COV_UNR"
Condition 219 "1239599449" "((chk_r_state_q == S_RESP) && chk_r_df_valid && ((~chk_a_r_busy)) && ((~chk_a_w_busy)) && ((~chk_r_parity_err))) 1 -1" (3 "11011")
ANNOTATION: "VC_COV_UNR"
Condition 219 "1239599449" "((chk_r_state_q == S_RESP) && chk_r_df_valid && ((~chk_a_r_busy)) && ((~chk_a_w_busy)) && ((~chk_r_parity_err))) 1 -1" (4 "11101")
ANNOTATION: "VC_COV_UNR"
Condition 231 "1070223480" "(chk_a_engn_wen_q && (engn_w_rdy_i || engn_w_err_i)) 1 -1" (2 "10")
ANNOTATION: "VC_COV_UNR"
Condition 232 "2394284170" "(engn_w_rdy_i || engn_w_err_i) 1 -1" (1 "00")
ANNOTATION: "VC_COV_UNR"
Condition 232 "2394284170" "(engn_w_rdy_i || engn_w_err_i) 1 -1" (2 "01")
ANNOTATION: "VC_COV_UNR"
Condition 235 "2202043314" "((chk_w_state_q == S_RESP) && (chk_w_df_valid || dw_end_advance) && ((~chk_a_r_busy)) && ((~chk_a_w_busy)) && ((~chk_w_parity_err))) 1 -1" (3 "11011")
ANNOTATION: "VC_COV_UNR"
Condition 235 "2202043314" "((chk_w_state_q == S_RESP) && (chk_w_df_valid || dw_end_advance) && ((~chk_a_r_busy)) && ((~chk_a_w_busy)) && ((~chk_w_parity_err))) 1 -1" (4 "11101")
ANNOTATION: "VC_COV_UNR"
Condition 257 "3478061144" "(((~chk_a_r_busy)) ? 1'b0 : chk_a_engn_ren_q) 1 -1" (1 "0")
ANNOTATION: "VC_COV_UNR"
Condition 259 "1689201132" "(((~chk_a_w_busy)) ? 1'b0 : chk_a_engn_wen_q) 1 -1" (1 "0")
ANNOTATION: "VC_COV_UNR"
Condition 262 "3568620287" "((((~chk_a_r_busy)) && ((~chk_a_w_busy))) ? 32'b0 : chk_a_engn_addr_q) 1 -1" (1 "0")
ANNOTATION: "VC_COV_UNR"
Condition 263 "4084947514" "(((~chk_a_r_busy)) && ((~chk_a_w_busy))) 1 -1" (1 "01")
ANNOTATION: "VC_COV_UNR"
Condition 263 "4084947514" "(((~chk_a_r_busy)) && ((~chk_a_w_busy))) 1 -1" (2 "10")
ANNOTATION: "VC_COV_UNR"
Condition 268 "2279218563" "(((~chk_a_w_busy)) ? ({DW {1'b0}}) : chk_a_engn_wdata_q) 1 -1" (1 "0")
ANNOTATION: "VC_COV_UNR"
Condition 270 "3322357894" "(((~chk_a_w_busy)) ? ({STRBW {1'b0}}) : chk_a_engn_wstrb_q) 1 -1" (1 "0")
ANNOTATION: "VC_COV_UNR"
Condition 273 "2681759955" "((((~chk_a_r_busy)) && ((~chk_a_w_busy))) ? ({IDW {1'b0}}) : chk_a_engn_id_q) 1 -1" (1 "0")
ANNOTATION: "VC_COV_UNR"
Condition 274 "3414452703" "(((~chk_a_r_busy)) && ((~chk_a_w_busy))) 1 -1" (1 "01")
ANNOTATION: "VC_COV_UNR"
Condition 274 "3414452703" "(((~chk_a_r_busy)) && ((~chk_a_w_busy))) 1 -1" (2 "10")
ANNOTATION: "VC_COV_UNR"
Condition 277 "3280877709" "((((~chk_a_r_busy)) && ((~chk_a_w_busy))) ? ({ENGNUW {1'b0}}) : chk_a_engn_user_q) 1 -1" (1 "0")
ANNOTATION: "VC_COV_UNR"
Condition 278 "547170628" "(((~chk_a_r_busy)) && ((~chk_a_w_busy))) 1 -1" (1 "01")
ANNOTATION: "VC_COV_UNR"
Condition 278 "547170628" "(((~chk_a_r_busy)) && ((~chk_a_w_busy))) 1 -1" (2 "10")
ANNOTATION: "VC_COV_UNR"
Condition 280 "1346455210" "(chk_a_read && chk_r_rdy_i && chk_valid_r_i && ((~chk_a_r_busy)) && ((~chk_a_w_busy)) && ( ~ (engn_ren_o && engn_r_err_i) ) && ((!internal_engn_r_parity_err))) 1 -1" (4 "1110111")
ANNOTATION: "VC_COV_UNR"
Condition 280 "1346455210" "(chk_a_read && chk_r_rdy_i && chk_valid_r_i && ((~chk_a_r_busy)) && ((~chk_a_w_busy)) && ( ~ (engn_ren_o && engn_r_err_i) ) && ((!internal_engn_r_parity_err))) 1 -1" (5 "1111011")
ANNOTATION: "VC_COV_UNR"
Condition 280 "1346455210" "(chk_a_read && chk_r_rdy_i && chk_valid_r_i && ((~chk_a_r_busy)) && ((~chk_a_w_busy)) && ( ~ (engn_ren_o && engn_r_err_i) ) && ((!internal_engn_r_parity_err))) 1 -1" (6 "1111101")
ANNOTATION: "VC_COV_UNR"
Condition 282 "3315994467" "(engn_ren_o && engn_r_err_i) 1 -1" (2 "10")
ANNOTATION: "VC_COV_UNR"
Condition 282 "3315994467" "(engn_ren_o && engn_r_err_i) 1 -1" (3 "11")
ANNOTATION: "VC_COV_UNR"
Condition 283 "3699167096" "(chk_a_write && chk_w_rdy_i && chk_valid_w_i && ((~chk_a_r_busy)) && ((~chk_a_w_busy)) && ( ~ (engn_wen_o && engn_w_err_i) ) && ((!internal_engn_w_parity_err))) 1 -1" (4 "1110111")
ANNOTATION: "VC_COV_UNR"
Condition 283 "3699167096" "(chk_a_write && chk_w_rdy_i && chk_valid_w_i && ((~chk_a_r_busy)) && ((~chk_a_w_busy)) && ( ~ (engn_wen_o && engn_w_err_i) ) && ((!internal_engn_w_parity_err))) 1 -1" (5 "1111011")
ANNOTATION: "VC_COV_UNR"
Condition 286 "3473097091" "(engn_ren_o && ( ~ (engn_r_rdy_i || engn_r_err_i) )) 1 -1" (3 "11")
ANNOTATION: "VC_COV_UNR"
Condition 288 "3739835813" "(engn_r_rdy_i || engn_r_err_i) 1 -1" (1 "00")
ANNOTATION: "VC_COV_UNR"
Condition 288 "3739835813" "(engn_r_rdy_i || engn_r_err_i) 1 -1" (2 "01")
ANNOTATION: "VC_COV_UNR"
Condition 289 "2773530068" "(engn_wen_o && ( ~ (engn_w_rdy_i || engn_w_err_i) )) 1 -1" (3 "11")
ANNOTATION: "VC_COV_UNR"
Condition 291 "4252322126" "(engn_w_rdy_i || engn_w_err_i) 1 -1" (1 "00")
ANNOTATION: "VC_COV_UNR"
Condition 291 "4252322126" "(engn_w_rdy_i || engn_w_err_i) 1 -1" (2 "01")
ANNOTATION: "VC_COV_UNR"
Condition 323 "3831376050" "(engn_ren_o && (engn_r_rdy_i || engn_r_err_i)) 1 -1" (2 "10")
ANNOTATION: "VC_COV_UNR"
Condition 324 "223411259" "(engn_r_rdy_i || engn_r_err_i) 1 -1" (1 "00")
ANNOTATION: "VC_COV_UNR"
Condition 324 "223411259" "(engn_r_rdy_i || engn_r_err_i) 1 -1" (2 "01")
ANNOTATION: "VC_COV_UNR"
Condition 325 "2834125268" "((chk_r_state_q == S_SERR) && chk_r_df_valid && ( ! (engn_ren_o && ((!engn_r_rdy_i))) )) 1 -1" (3 "110")
ANNOTATION: "VC_COV_UNR"
Condition 327 "3948531734" "( ! (engn_ren_o && ((!engn_r_rdy_i))) ) 1 -1" (2 "1")
ANNOTATION: "VC_COV_UNR"
Condition 328 "2329644844" "(engn_ren_o && ((!engn_r_rdy_i))) 1 -1" (2 "10")
ANNOTATION: "VC_COV_UNR"
Condition 328 "2329644844" "(engn_ren_o && ((!engn_r_rdy_i))) 1 -1" (3 "11")
ANNOTATION: "VC_COV_UNR"
Condition 373 "787471941" "(axi_w_wlast_err && ((~chk_a_r_busy)) && ((~chk_a_w_busy))) 1 -1" (2 "101")
ANNOTATION: "VC_COV_UNR"
Condition 373 "787471941" "(axi_w_wlast_err && ((~chk_a_r_busy)) && ((~chk_a_w_busy))) 1 -1" (3 "110")
CHECKSUM: "3065175588 13221216"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_cmu_ctrl
ANNOTATION: "VC_COV_UNR"
Condition 18 "1330990567" "(c_wrap_cmd_comp & ((~c_wrap_cmd_err))) 1 -1" (1 "01")
CHECKSUM: "3284043580 1490894522"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_axi_sub_wrap
ANNOTATION: "VC_COV_UNR"
Condition 1 "2858976932" "(csr_rdy & sub_engn_ren_o) 1 -1" (1 "01")
ANNOTATION: "VC_COV_UNR"
Condition 2 "2539007574" "(csr_rdy & sub_engn_wen_o) 1 -1" (1 "01")
CHECKSUM: "1001877921 2676189987"
MODULE: \IP_SINC_RTL.sinc_top
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sinc_axi_mgr_araddr [0] "logic sinc_axi_mgr_araddr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sinc_axi_mgr_araddr [1] "logic sinc_axi_mgr_araddr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sinc_axi_mgr_awaddr [0] "logic sinc_axi_mgr_awaddr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sinc_axi_mgr_awaddr [1] "logic sinc_axi_mgr_awaddr[31:0]"
ANNOTATION: "VC_COV_UNR"
Toggle 0to1 sinc_axi_sub_bresp [0] "logic sinc_axi_sub_bresp[1:0]"
