//==================================================
// This file contains the Excluded objects
// Format Version: 2
// Date: Tue Nov  5 10:15:22 2024
// ExclMode: default
//==================================================
CHECKSUM: "1049511595"
INSTANCE:hdl_top.sinc.u_sinc_cmu.u_axi_sub_wrap.u_axi_sub
CHECKSUM: "2358002164 311475779"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_crypto_wrap.u_crypto_wrap_ctrl
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_din_aad_sel "logic aes_test_din_aad_sel"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle wdata_bt_cnt "logic wdata_bt_cnt[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle rdata_bt_cnt "logic rdata_bt_cnt[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_ctrl_state "logic aes_ctrl_state[6:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_ctrl_sub_state "logic aes_ctrl_sub_state[5:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_block_cnt "logic aes_block_cnt[5:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle c_wrap_dma_caddr "logic c_wrap_dma_caddr[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle next_aes_ctrl_sub_state "logic next_aes_ctrl_sub_state[5:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle din_bytecnt_i "logic din_bytecnt_i[4:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mode_i "logic mode_i[3:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_mode_q "logic aes_test_mode_q[3:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_mode "logic aes_test_mode[3:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_key_len "logic aes_test_key_len[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_ctrl "logic aes_test_ctrl[17:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle cmu_ctrl_cmd "logic cmu_ctrl_cmd[9:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_din_bytecnt "logic aes_test_din_bytecnt[4:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle key_size_i "logic key_size_i[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle invld_din_bytecnt "logic invld_din_bytecnt"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle fault_err_o "logic fault_err_o[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle disable_encr_auth_check_i "logic disable_encr_auth_check_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_din_err "logic aes_test_din_err"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle seed_i "logic seed_i[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle encr_block_sts "logic encr_block_sts[11:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle encr_block_cnt "logic encr_block_cnt[11:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle invld_din_aad_sel "logic invld_din_aad_sel"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle din_aad_sel_i "logic din_aad_sel_i"
CHECKSUM: "3380745230 67991534"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_dma
ANNOTATION: "Sub module toggle coverage is waived."
Toggle dma_w_len_mux "logic dma_w_len_mux[29:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle dma_r_last_beat "logic dma_r_last_beat[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle w_beat_cnt "logic w_beat_cnt[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle r_beat_cnt "logic r_beat_cnt[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle dma_w_last_beat "logic dma_w_last_beat[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mgr_engn_craddr_i "logic mgr_engn_craddr_i[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle dma_r_addr_q "logic dma_r_addr_q[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle dma_r_addr_mux "logic dma_r_addr_mux[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle c_wrap_dma_caddr "logic c_wrap_dma_caddr[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mgr_engn_cwaddr_i "logic mgr_engn_cwaddr_i[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle dma_w_addr_q "logic dma_w_addr_q[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle dma_w_addr_mux "logic dma_w_addr_mux[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mgr_engn_cwlen_i "logic mgr_engn_cwlen_i[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle dma_w_len_q "logic dma_w_len_q[7:0]"
CHECKSUM: "3666800856 3189680496"
INSTANCE: hdl_top.sinc.u_sinc_cmu
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_ctrl_data_in_valid_input "logic aes_test_ctrl_data_in_valid_input"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sub_engn_w_rdy_i "logic sub_engn_w_rdy_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sub_engn_w_err_i "logic sub_engn_w_err_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sub_engn_rdata_i "logic sub_engn_rdata_i[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sub_engn_r_rdy_i "logic sub_engn_r_rdy_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sub_engn_r_err_i "logic sub_engn_r_err_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle status_state_load_enable "logic status_state_load_enable"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle status_state_input "logic status_state_input[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle status_sinc_reset_disabled "logic status_sinc_reset_disabled"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle status_sinc_reinit_disabled "logic status_sinc_reinit_disabled"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle status_cmd_status_load_enable "logic status_cmd_status_load_enable"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle status_cmd_status_input "logic status_cmd_status_input[3:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle state "logic state[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_mgr_ruser "logic sinc_axi_mgr_ruser[11:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_mgr_rid "logic sinc_axi_mgr_rid[0:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_mgr_buser "logic sinc_axi_mgr_buser[11:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_mgr_bid "logic sinc_axi_mgr_bid[0:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_mgr_awprot "logic sinc_axi_mgr_awprot[2:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_mgr_awid "logic sinc_axi_mgr_awid[0:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_mgr_arprot "logic sinc_axi_mgr_arprot[2:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_mgr_arid "logic sinc_axi_mgr_arid[0:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle rd_en "logic rd_en"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle intsts_err_state_load_enable "logic intsts_err_state_load_enable"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle intsts_err_state_input "logic intsts_err_state_input"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle chk_w_rdy_i "logic chk_w_rdy_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle chk_valid_w_i "logic chk_valid_w_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle chk_valid_r_i "logic chk_valid_r_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle chk_r_rdy_i "logic chk_r_rdy_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle chk_invalid_w_i "logic chk_invalid_w_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle chk_invalid_r_i "logic chk_invalid_r_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_ctrl_test_en_load_enable "logic aes_test_ctrl_test_en_load_enable"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_ctrl_test_en_input "logic aes_test_ctrl_test_en_input"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_ctrl_set_key_and_iv_load_enable "logic aes_test_ctrl_set_key_and_iv_load_enable"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_ctrl_set_key_and_iv_input "logic aes_test_ctrl_set_key_and_iv_input"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_ctrl_data_out_ack_load_enable "logic aes_test_ctrl_data_out_ack_load_enable"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_ctrl_data_out_ack_input "logic aes_test_ctrl_data_out_ack_input"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_ctrl_data_in_valid_load_enable "logic aes_test_ctrl_data_in_valid_load_enable"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle wr_en "logic wr_en"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle csr_addr "logic csr_addr[9:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_mgr_araddr "logic sinc_axi_mgr_araddr[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mgr_engn_craddr_i "logic mgr_engn_craddr_i[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle c_wrap_dma_caddr "logic c_wrap_dma_caddr[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_mgr_awaddr "logic sinc_axi_mgr_awaddr[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mgr_engn_cwaddr_i "logic mgr_engn_cwaddr_i[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_awaddr "logic sinc_axi_sub_awaddr[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_ctrl "logic aes_test_ctrl[17:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_araddr "logic sinc_axi_sub_araddr[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle cmu_ctrl_cmd "logic cmu_ctrl_cmd[9:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_bresp "logic sinc_axi_sub_bresp[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_awsize "logic sinc_axi_sub_awsize[2:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_arsize "logic sinc_axi_sub_arsize[2:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mgr_engn_cwlen_i "logic mgr_engn_cwlen_i[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_awlen "logic sinc_axi_sub_awlen[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_arlen "logic sinc_axi_sub_arlen[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle disable_encr_auth_check_i "logic disable_encr_auth_check_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle encr_block_sts "logic encr_block_sts[11:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_mgr_awuser "logic sinc_axi_mgr_awuser[11:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_mgr_aruser "logic sinc_axi_mgr_aruser[11:0]"
CHECKSUM: "1887489418 67833329"
INSTANCE: hdl_top.sinc.u_sinc_ciu
ANNOTATION: "Sub module toggle coverage is waived."
Toggle cpu_read_upon_accvio "logic cpu_read_upon_accvio"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mem_err_inject_addr "net mem_err_inject_addr[13:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mpu_reg_addr "net mpu_reg_addr[12:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mem_err_corr "logic mem_err_corr[2:0]"
CHECKSUM: "3055974457 3912678340"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_crypto_wrap
ANNOTATION: "Sub module toggle coverage is waived."
Toggle din_aad_sel_i "logic din_aad_sel_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle unused_ib_entries_in_use "logic unused_ib_entries_in_use[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle c_wrap_dma_caddr "logic c_wrap_dma_caddr[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle dout_bytecnt_o_unused "logic dout_bytecnt_o_unused[4:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle din_bytecnt_i "logic din_bytecnt_i[4:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mode_i "logic mode_i[3:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_ctrl "logic aes_test_ctrl[17:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle cmu_ctrl_cmd "logic cmu_ctrl_cmd[9:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle key_size_i "logic key_size_i[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle fault_err_o "logic fault_err_o[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle disable_encr_auth_check_i "logic disable_encr_auth_check_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle seed_i "logic seed_i[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle encr_block_sts "logic encr_block_sts[11:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle unused_ib_underflow_err "logic unused_ib_underflow_err"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle unused_ib_push_rdy "logic unused_ib_push_rdy"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle unused_ib_overflow_err "logic unused_ib_overflow_err"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle unused_ib_full "logic unused_ib_full"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle state "logic state[6:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle next_state "logic next_state[6:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle is_state_fetch_block "logic is_state_fetch_block"
CHECKSUM: "3065175588 849475124"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_cmu_ctrl
ANNOTATION: "Sub module toggle coverage is waived."
Toggle set_cmd_complete "logic set_cmd_complete"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle cmu_ctrl_cmd "logic cmu_ctrl_cmd[9:0]"
CHECKSUM: "1432683219 3019469556"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_crypto_wrap.u_crypto_wrap_ctrl.u_sinc_cmu_crypto_wrap_ctrl_ret
ANNOTATION: "Sub module toggle coverage is waived."
Toggle rdata_bt_cnt [7] "logic rdata_bt_cnt[7:0]"
CHECKSUM: "4257887522 1616668096"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_reg_ctrl.u_sinc_regs
ANNOTATION: "Waivable generated module."
Toggle csr_internal_field_hit_cntr_upper_hit_cntr_upper "net csr_internal_field_hit_cntr_upper_hit_cntr_upper[15:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_field_lat_cntr_upper_lat_cntr_upper "net csr_internal_field_lat_cntr_upper_lat_cntr_upper[15:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_field_miss_cntr_upper_miss_cntr_upper "net csr_internal_field_miss_cntr_upper_miss_cntr_upper[15:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_input_hit_cntr_upper_hit_cntr_upper "net csr_internal_input_hit_cntr_upper_hit_cntr_upper[15:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_input_lat_cntr_upper_lat_cntr_upper "net csr_internal_input_lat_cntr_upper_lat_cntr_upper[15:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_input_miss_cntr_upper_miss_cntr_upper "net csr_internal_input_miss_cntr_upper_miss_cntr_upper[15:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_next_field_aes_test_ctrl_data_in_aad_sel "net csr_internal_next_field_aes_test_ctrl_data_in_aad_sel"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_bus_hit_cntr_upper "net csr_internal_read_bus_hit_cntr_upper[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_bus_lat_cntr_upper "net csr_internal_read_bus_lat_cntr_upper[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_bus_miss_cntr_upper "net csr_internal_read_bus_miss_cntr_upper[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_value_hit_cntr_upper "net csr_internal_read_value_hit_cntr_upper[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_value_lat_cntr_upper "net csr_internal_read_value_lat_cntr_upper[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_value_miss_cntr_upper "net csr_internal_read_value_miss_cntr_upper[31:0]"
ANNOTATION: "Waivable generated module."
Toggle hit_cntr_upper_hit_cntr_upper "net hit_cntr_upper_hit_cntr_upper[15:0]"
ANNOTATION: "Waivable generated module."
Toggle lat_cntr_upper_lat_cntr_upper "net lat_cntr_upper_lat_cntr_upper[15:0]"
ANNOTATION: "Waivable generated module."
Toggle miss_cntr_upper_miss_cntr_upper "net miss_cntr_upper_miss_cntr_upper[15:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_bus_encr_block_status "net csr_internal_read_bus_encr_block_status[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_bus_hit_cntr_lower "net csr_internal_read_bus_hit_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_field_hit_cntr_lower_hit_cntr_lower "net csr_internal_field_hit_cntr_lower_hit_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_input_hit_cntr_lower_hit_cntr_lower "net csr_internal_input_hit_cntr_lower_hit_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_value_hit_cntr_lower "net csr_internal_read_value_hit_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle hit_cntr_lower_hit_cntr_lower "net hit_cntr_lower_hit_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_field_miss_cntr_lower_miss_cntr_lower "net csr_internal_field_miss_cntr_lower_miss_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_input_miss_cntr_lower_miss_cntr_lower "net csr_internal_input_miss_cntr_lower_miss_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_bus_miss_cntr_lower "net csr_internal_read_bus_miss_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_value_miss_cntr_lower "net csr_internal_read_value_miss_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle miss_cntr_lower_miss_cntr_lower "net miss_cntr_lower_miss_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_field_encr_block_status_num_of_blocks_encr "reg csr_internal_field_encr_block_status_num_of_blocks_encr[11:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_next_field_encr_block_status_num_of_blocks_encr "net csr_internal_next_field_encr_block_status_num_of_blocks_encr[11:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_effect_encr_block_status_num_of_blocks_encr "net csr_internal_read_effect_encr_block_status_num_of_blocks_encr[11:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_value_encr_block_status "net csr_internal_read_value_encr_block_status[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_input_encr_block_status_num_of_blocks_encr "net csr_internal_input_encr_block_status_num_of_blocks_encr[11:0]"
ANNOTATION: "Waivable generated module."
Toggle encr_block_status_num_of_blocks_encr_input "net encr_block_status_num_of_blocks_encr_input[11:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_bus_aes_test_ctrl "net csr_internal_read_bus_aes_test_ctrl[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_bus_lat_cntr_lower "net csr_internal_read_bus_lat_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_field_lat_cntr_lower_lat_cntr_lower "net csr_internal_field_lat_cntr_lower_lat_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_input_lat_cntr_lower_lat_cntr_lower "net csr_internal_input_lat_cntr_lower_lat_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_value_lat_cntr_lower "net csr_internal_read_value_lat_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle lat_cntr_lower_lat_cntr_lower "net lat_cntr_lower_lat_cntr_lower[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_field_aes_test_ctrl_data_in_byte_cnt "reg csr_internal_field_aes_test_ctrl_data_in_byte_cnt[4:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_next_field_aes_test_ctrl_data_in_byte_cnt "net csr_internal_next_field_aes_test_ctrl_data_in_byte_cnt[4:0]"
ANNOTATION: "Waivable generated module."
Toggle aes_test_ctrl "net aes_test_ctrl[17:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_field_aes_test_ctrl_key_len "reg csr_internal_field_aes_test_ctrl_key_len[1:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_field_aes_test_ctrl_mode "reg csr_internal_field_aes_test_ctrl_mode[3:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_next_field_aes_test_ctrl_key_len "net csr_internal_next_field_aes_test_ctrl_key_len[1:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_next_field_aes_test_ctrl_mode "net csr_internal_next_field_aes_test_ctrl_mode[3:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_read_value_aes_test_ctrl "net csr_internal_read_value_aes_test_ctrl[31:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_addr "net csr_addr[9:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_bus_address "net csr_internal_bus_address[9:0]"
ANNOTATION: "Waivable generated module."
Toggle csr_internal_field_aes_test_ctrl_data_in_aad_sel "reg csr_internal_field_aes_test_ctrl_data_in_aad_sel"
CHECKSUM: "3828278263 1306208368"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_crypto_wrap.u_input_buf
ANNOTATION: "Sub module toggle coverage is waived."
Toggle almost_full "logic almost_full"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle entries_in_use "logic entries_in_use[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle pop_ptr_q.ptr "logic pop_ptr_q.ptr[6:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle pop_ptr_din.ptr "logic pop_ptr_din.ptr[6:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle unused_push_addr "logic unused_push_addr[6:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle unused_pop_addr "logic unused_pop_addr[4:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle underflow_err "logic underflow_err"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle push_rdy "logic push_rdy"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle pop_ptr_pos "logic pop_ptr_pos[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle overflow_err "logic overflow_err"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle gen_push_less_than_pop_block.unused_pop_ptr_pos "logic gen_push_less_than_pop_block.unused_pop_ptr_pos[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle full "logic full"
CHECKSUM: "3828278263 2958624279"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_crypto_wrap.u_output_buf
ANNOTATION: "Sub module toggle coverage is waived."
Toggle almost_empty "logic almost_empty"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle unused_push_addr "logic unused_push_addr[0:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle unused_pop_addr "logic unused_pop_addr[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle underflow_err "logic underflow_err"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle push_ptr_q.ptr "logic push_ptr_q.ptr[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle push_ptr_pos "logic push_ptr_pos[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle push_ptr_din.ptr "logic push_ptr_din.ptr[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle overflow_err "logic overflow_err"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle gen_pop_less_than_pop_block.unused_push_ptr_pos "logic gen_pop_less_than_pop_block.unused_push_ptr_pos[1:0]"
CHECKSUM: "3284043580 4019309916"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_axi_sub_wrap
ANNOTATION: "Sub module toggle coverage is waived."
Toggle unused_sub_engn_user_o "logic unused_sub_engn_user_o[11:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle csr_addr "logic csr_addr[9:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_awaddr "logic sinc_axi_sub_awaddr[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle chk_addr_o "logic chk_addr_o[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_araddr "logic sinc_axi_sub_araddr[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sub_engn_addr_o "logic sub_engn_addr_o[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_bresp "logic sinc_axi_sub_bresp[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_awsize "logic sinc_axi_sub_awsize[2:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_arsize "logic sinc_axi_sub_arsize[2:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle chk_size_o "logic chk_size_o[2:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_awlen "logic sinc_axi_sub_awlen[7:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sinc_axi_sub_arlen "logic sinc_axi_sub_arlen[7:0]"
CHECKSUM: "3019501273 1893824282"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_reg_ctrl
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_data_out_0_aes_test_data_out_0_load_enable "logic aes_test_data_out_0_aes_test_data_out_0_load_enable"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle csr_addr "logic csr_addr[9:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_ctrl "logic aes_test_ctrl[17:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle lat_cntr "logic lat_cntr[47:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle encr_block_sts "logic encr_block_sts[11:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle miss_cntr "logic miss_cntr[47:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle hit_cntr "logic hit_cntr[47:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sts_sinc_reset_disabled "logic sts_sinc_reset_disabled"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sts_sinc_reinit_disabled "logic sts_sinc_reinit_disabled"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sts_sinc_hw_fault_load_enable "logic sts_sinc_hw_fault_load_enable"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sts_sinc_hw_fault_input "logic sts_sinc_hw_fault_input"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle sts_aes_err_input "logic sts_aes_err_input"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle miss_cntr_max "logic miss_cntr_max"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle lat_cntr_max "logic lat_cntr_max"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle hit_cntr_max "logic hit_cntr_max"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_sts_dout_vld_q "logic aes_test_sts_dout_vld_q"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_data_out_3_aes_test_data_out_3_load_enable "logic aes_test_data_out_3_aes_test_data_out_3_load_enable"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_data_out_2_aes_test_data_out_2_load_enable "logic aes_test_data_out_2_aes_test_data_out_2_load_enable"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aes_test_data_out_1_aes_test_data_out_1_load_enable "logic aes_test_data_out_1_aes_test_data_out_1_load_enable"
CHECKSUM: "888486822 3979931167"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_crypto_wrap.u_gp_aes.u_gp_aes_mode.u_gp_aes_inc32
ANNOTATION: "Sub module toggle coverage is waived."
Toggle in_plus_1 "logic in_plus_1[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle inc32_out "logic inc32_out[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle inc32_in "logic inc32_in[127:0]"
CHECKSUM: "354253666 882906417"
INSTANCE: hdl_top.sinc.u_sinc_ciu.u_ciu_vtag
ANNOTATION: "Sub module toggle coverage is waived."
Toggle parity_pass "logic parity_pass[3:0]"
CHECKSUM: "2349709650 3541158047"
INSTANCE: hdl_top.sinc.u_sinc_ciu.u_ciu_ctrl
Fsm ciu_cache_sm_r "3122356135"
Transition CIU_RREAD->CIU_IDLE "42->0"
Fsm ciu_cache_sm_r "3122356135"
Transition CIU_CACHE_MISS->CIU_IDLE "30->0"
Fsm ciu_cache_sm_r "3122356135"
Transition CIU_EXTRA->CIU_IDLE "51->0"
Fsm ciu_cache_sm_r "3122356135"
Transition CIU_MEM_READ->CIU_IDLE "7->0"
CHECKSUM: "4257887522 1958158551"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_reg_ctrl.u_sinc_regs
ANNOTATION: "Waivable generated module."
Condition 513 "144668605" "(csr_internal_read_value_miss_cntr_lower & ({32 {csr_internal_decode_miss_cntr_lower}})) 32 -1"
ANNOTATION: "Waivable generated module."
Condition 1012 "3625244457" "(csr_internal_decode_aes_test_ctrl & csr_internal_write_enable_aes_test_ctrl_data_out_ack & csr_internal_write_access) 1 -1"
ANNOTATION: "Waivable generated module."
Condition 479 "3021823376" "(csr_internal_read_value_hit_cntr_upper & ({32 {csr_internal_decode_hit_cntr_upper}})) 32 -1"
ANNOTATION: "Waivable generated module."
Condition 615 "4109608182" "(csr_internal_read_value_lat_cntr_upper & ({32 {csr_internal_decode_lat_cntr_upper}})) 32 -1"
ANNOTATION: "Waivable generated module."
Condition 547 "3197981817" "(csr_internal_read_value_miss_cntr_upper & ({32 {csr_internal_decode_miss_cntr_upper}})) 32 -1"
ANNOTATION: "Waivable generated module."
Condition 1073 "829088933" "(csr_internal_read_value_encr_block_status & ({32 {csr_internal_decode_encr_block_status}})) 32 -1"
ANNOTATION: "Waivable generated module."
Condition 581 "213355571" "(csr_internal_read_value_lat_cntr_lower & ({32 {csr_internal_decode_lat_cntr_lower}})) 32 -1"
ANNOTATION: "Waivable generated module."
Condition 1024 "1390780002" "(csr_internal_decode_aes_test_ctrl & csr_internal_write_enable_aes_test_ctrl_cfg_key_iv_vld & csr_internal_write_access) 1 -1"
ANNOTATION: "Waivable generated module."
Condition 1015 "1954397933" "(csr_internal_decode_aes_test_ctrl & csr_internal_write_enable_aes_test_ctrl_data_in_aad_sel & csr_internal_write_access) 1 -1"
ANNOTATION: "Waivable generated module."
Condition 1019 "3306170507" "(csr_internal_decode_aes_test_ctrl & csr_internal_write_enable_aes_test_ctrl_data_in_byte_cnt & csr_internal_write_access) 1 -1"
ANNOTATION: "Waivable generated module."
Condition 1017 "4204559764" "(csr_internal_decode_aes_test_ctrl & csr_internal_write_enable_aes_test_ctrl_data_in_last & csr_internal_write_access) 1 -1"
ANNOTATION: "Waivable generated module."
Condition 1021 "900048132" "(csr_internal_decode_aes_test_ctrl & csr_internal_write_enable_aes_test_ctrl_data_in_vld & csr_internal_write_access) 1 -1"
ANNOTATION: "Waivable generated module."
Condition 1031 "1613434545" "(csr_internal_decode_aes_test_ctrl & csr_internal_write_enable_aes_test_ctrl_dir & csr_internal_write_access) 1 -1"
ANNOTATION: "Waivable generated module."
Condition 1029 "3838682131" "(csr_internal_decode_aes_test_ctrl & csr_internal_write_enable_aes_test_ctrl_key_len & csr_internal_write_access) 1 -1"
ANNOTATION: "Waivable generated module."
Condition 1033 "2327823258" "(csr_internal_decode_aes_test_ctrl & csr_internal_write_enable_aes_test_ctrl_mode & csr_internal_write_access) 1 -1"
ANNOTATION: "Waivable generated module."
Condition 1027 "3926371779" "(csr_internal_decode_aes_test_ctrl & csr_internal_write_enable_aes_test_ctrl_reuse_key & csr_internal_write_access) 1 -1"
ANNOTATION: "Waivable generated module."
Condition 1110 "1439650929" "(csr_internal_read_bus_block_encr_num | csr_internal_read_bus_num_of_blocks | csr_internal_read_bus_block_encr_addr | csr_internal_read_bus_block_encr_key | csr_internal_read_bus_aes_iv_nonce_0 | csr_internal_read_bus_aes_iv_nonce_1 | csr_internal_read_bus_aes_iv_nonce_2 | csr_internal_read_bus_ext_block_base_addr | csr_internal_read_bus_ext_auth_tag_base_addr | csr_internal_read_bus_status | csr_internal_read_bus_hit_cntr_lower | csr_internal_read_bus_hit_cntr_upper | csr_internal_read_bus_miss_cntr_lower | csr_internal_read_bus_miss_cntr_upper | csr_internal_read_bus_lat_cntr_lower | csr_internal_read_bus_lat_cntr_upper | csr_internal_read_bus_perf_cntr_ctrl | csr_internal_read_bus_aes_test_data_in_0 | csr_internal_read_bus_aes_test_data_in_1 | csr_internal_read_bus_aes_test_data_in_2 | csr_internal_read_bus_aes_test_data_in_3 | csr_internal_read_bus_aes_test_data_out_0 | csr_internal_read_bus_aes_test_data_out_1 | csr_internal_read_bus_aes_test_data_out_2 | csr_internal_read_bus_aes_test_data_out_3 | csr_internal_read_bus_aes_test_ctrl | csr_internal_read_bus_aes_test_status | csr_internal_read_bus_encr_block_status) 32 -1"
ANNOTATION: "Waivable generated module."
Condition 979 "4179258034" "(csr_internal_read_value_aes_test_ctrl & ({32 {csr_internal_decode_aes_test_ctrl}})) 32 -1"
ANNOTATION: "Waivable generated module."
Condition 445 "1280931157" "(csr_internal_read_value_hit_cntr_lower & ({32 {csr_internal_decode_hit_cntr_lower}})) 32 -1"
CHECKSUM: "4283262166 3029102466"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_axi_sub_wrap.u_axi_sub_checker
ANNOTATION: "Sub module toggle coverage is waived."
Toggle chk_size_o "logic chk_size_o[2:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle chk_addr_o "logic chk_addr_o[31:0]"
CHECKSUM: "2349709650 3048346851"
INSTANCE: hdl_top.sinc.u_sinc_ciu.u_ciu_ctrl
ANNOTATION: "Sub module toggle coverage is waived."
Toggle cpu_access_upon_mpu_busy "logic cpu_access_upon_mpu_busy"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle pending_cpu_mem_read_r "logic pending_cpu_mem_read_r"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle pending_cpu_access_upon_cache_failed_r "logic pending_cpu_access_upon_cache_failed_r"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle nxt_pending_cpu_mem_read "logic nxt_pending_cpu_mem_read"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle nxt_pending_cpu_access_upon_cache_failed "logic nxt_pending_cpu_access_upon_cache_failed"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle cpu_read_upon_accvio "logic cpu_read_upon_accvio"
CHECKSUM: "1001877921 2676189987"
INSTANCE: hdl_top.sinc
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_mgr_arid "logic sinc_axi_mgr_arid[0:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_sub_bresp [0] "logic sinc_axi_sub_bresp[1:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_sub_arsize [2] "logic sinc_axi_sub_arsize[2:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_err_corr_o "logic sinc_err_corr_o[2:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_mgr_awuser "logic sinc_axi_mgr_awuser[11:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_mgr_aruser "logic sinc_axi_mgr_aruser[11:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_mgr_ruser "logic sinc_axi_mgr_ruser[11:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_mgr_rid "logic sinc_axi_mgr_rid[0:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_mgr_buser "logic sinc_axi_mgr_buser[11:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_mgr_bid "logic sinc_axi_mgr_bid[0:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_mgr_awprot "logic sinc_axi_mgr_awprot[2:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_mgr_awid "logic sinc_axi_mgr_awid[0:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_mgr_arprot "logic sinc_axi_mgr_arprot[2:0]"
ANNOTATION: "Not critical to test, verified bad length request in a prior project."
Toggle sinc_axi_sub_arlen [7] "logic sinc_axi_sub_arlen[7:0]"
ANNOTATION: "Not critical to test, verified bad length request in a prior project."
Toggle sinc_axi_sub_arlen [5] "logic sinc_axi_sub_arlen[7:0]"
ANNOTATION: "Not critical to test, verified bad length request in a prior project."
Toggle sinc_axi_sub_arlen [6] "logic sinc_axi_sub_arlen[7:0]"
ANNOTATION: "Not critical to test, verified bad length request in a prior project."
Toggle sinc_axi_sub_awlen [7] "logic sinc_axi_sub_awlen[7:0]"
ANNOTATION: "Not critical to test, verified bad length request in a prior project."
Toggle sinc_axi_sub_awlen [5] "logic sinc_axi_sub_awlen[7:0]"
ANNOTATION: "Not critical to test, verified bad length request in a prior project."
Toggle sinc_axi_sub_awlen [6] "logic sinc_axi_sub_awlen[7:0]"
ANNOTATION: "Unsupported test case in SINC config."
Toggle sinc_axi_sub_araddr [30] "logic sinc_axi_sub_araddr[31:0]"
ANNOTATION: "Unsupported test case in SINC config."
Toggle sinc_axi_sub_araddr [28] "logic sinc_axi_sub_araddr[31:0]"
ANNOTATION: "Unsupported test case in SINC config."
Toggle sinc_axi_sub_araddr [29] "logic sinc_axi_sub_araddr[31:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_mgr_araddr "logic sinc_axi_mgr_araddr[31:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_mgr_awaddr "logic sinc_axi_mgr_awaddr[31:0]"
ANNOTATION: "Unsupported test case in SINC config."
Toggle sinc_axi_sub_awaddr [30] "logic sinc_axi_sub_awaddr[31:0]"
ANNOTATION: "Unsupported test case in SINC config."
Toggle sinc_axi_sub_awaddr [28] "logic sinc_axi_sub_awaddr[31:0]"
ANNOTATION: "Unsupported test case in SINC config."
Toggle sinc_axi_sub_awaddr [29] "logic sinc_axi_sub_awaddr[31:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_sub_awaddr "logic sinc_axi_sub_awaddr[31:0]"
ANNOTATION: "Output of design is fixed"
Toggle sinc_axi_sub_araddr "logic sinc_axi_sub_araddr[31:0]"
ANNOTATION: "Byte access is fixed."
Toggle sinc_mpu_reg_addr_i [1] "logic sinc_mpu_reg_addr_i[12:0]"
ANNOTATION: "Byte access is fixed."
Toggle sinc_mpu_reg_addr_i [0] "logic sinc_mpu_reg_addr_i[12:0]"
ANNOTATION: "Not critical to test"
Toggle sinc_err_inject_addr_i [2] "logic sinc_err_inject_addr_i[13:0]"
CHECKSUM: "880081607 538719604"
INSTANCE: hdl_top
Toggle mem_err_corr_o "logic mem_err_corr_o[2:0]"
Toggle cache_mem_addr_w "logic cache_mem_addr_w[14:0]"
Toggle cache_vtag_addr_w "logic cache_vtag_addr_w[7:0]"
Toggle clkg_override "logic clkg_override"
CHECKSUM: "1077508457 3299518390"
INSTANCE: hdl_top.sinc.u_sinc_cmu.u_crypto_wrap.u_gp_aes.u_gp_aes_mode
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aad_cnt "logic aad_cnt[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle dout_bytecnt_o "logic dout_bytecnt_o[4:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle din_bytecnt_i "logic din_bytecnt_i[4:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle bytecnt "logic bytecnt[4:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle iv_unswap "logic iv_unswap[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle iv_swap "logic iv_swap[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle iv_r "logic iv_r[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle iv_plus_1 "logic iv_plus_1[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle iv_nxt "logic iv_nxt[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle inc32_out_unswap "logic inc32_out_unswap[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle inc32_out_swap "logic inc32_out_swap[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle inc32_in_unswap "logic inc32_in_unswap[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle inc32_in_swap "logic inc32_in_swap[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mode_q "logic mode_q[3:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle mode_i "logic mode_i[3:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle nk_o "logic nk_o[3:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle nr_o "logic nr_o[3:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle next_state "logic next_state[5:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle key_size_q "logic key_size_q[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle key_size_i "logic key_size_i[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle key_size "logic key_size[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle fault_err_o "logic fault_err_o[1:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle din_bytecnt_q "logic [1:0][4:0]din_bytecnt_q"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle cur_state "logic cur_state[5:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle seed_i "logic seed_i[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle seed_q "logic seed_q[639:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle seed_o "logic [3:0][159:0]seed_o"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle msg_cnt_bits "logic msg_cnt_bits[34:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle msg_cnt "logic msg_cnt[31:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle ghash_len "logic ghash_len[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle ghash_len_bit_swap "logic ghash_len_bit_swap[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle unit_cnt "logic unit_cnt[8:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle temp_1d "logic temp_1d[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle s_key1 "logic s_key1"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle s_key0 "logic s_key0"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle s_data1 "logic s_data1"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle key_size_err "logic key_size_err"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle iv_i_swap "logic iv_i_swap[127:0]"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle invld_cur_state "logic invld_cur_state"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle invld_core_in_state "logic invld_core_in_state"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle i_valid_r "logic i_valid_r"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle eou "logic eou"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle din_aad_sel_i "logic din_aad_sel_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle ctx_err "logic ctx_err"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle core_fault_i "logic core_fault_i"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle cfg_err "logic cfg_err"
ANNOTATION: "Sub module toggle coverage is waived."
Toggle aad_cnt_bits "logic aad_cnt_bits[34:0]"
