# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# File          : bom.yml
# Description   : microsoft internal compile file describing IP groups, file lists, and dependencies for open_sinc

schema_version: '1.1.0'

---
name: ip_axi_mgr_rtl
logical_groups:
  rtl:
    incdirs:
      - ${COMPILE_ROOT}/../sinc/include
    files:
      - ${COMPILE_ROOT}/rtl/axi_mgr.v
    tops: [axi_mgr]