// Copyright (c) Microsoft Corporation and contributors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// File        : sinc_features_pkg.sv
// Description : This package contains variables representing all the SINC feature key/value pairs.

`ifndef SINC_FEATURES_PKG
`define SINC_FEATURES_PKG

package sinc_features_pkg;
  import uvm_pkg::*;
  import sinc_parameters_pkg::*;

  //========================================//
  // SINC access control feature define     //
  //                                        //
  // List of all features per SINC MAS view //
  //========================================//

  static const bit FEATURE_NAME_HASH[string] = '{
    "CMD_REG_EXIST":`SINC_CMD_REG_EXIST,
    "CMD_REG_WR":`SINC_CMD_REG_WRITE_ALLOWED,
    "CMD_REG_RD":`SINC_CMD_REG_READ_ALLOWED,
    "CMD_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_CMD_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "CMD_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_CMD_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "CMD_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_CMD_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "CMD_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_CMD_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "BLOCK_ENCR_NUM_REG_EXIST":`SINC_BLOCK_ENCR_NUM_REG_EXIST,
    "BLOCK_ENCR_NUM_REG_WR":`SINC_BLOCK_ENCR_NUM_REG_WRITE_ALLOWED,
    "BLOCK_ENCR_NUM_REG_RD":`SINC_BLOCK_ENCR_NUM_REG_READ_ALLOWED,
    "BLOCK_ENCR_NUM_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_BLOCK_ENCR_NUM_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "BLOCK_ENCR_NUM_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_BLOCK_ENCR_NUM_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "BLOCK_ENCR_NUM_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_BLOCK_ENCR_NUM_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "BLOCK_ENCR_NUM_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_BLOCK_ENCR_NUM_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "NUM_OF_BLOCKS_REG_EXIST":`SINC_NUM_OF_BLOCKS_REG_EXIST,
    "NUM_OF_BLOCKS_REG_WR":`SINC_NUM_OF_BLOCKS_REG_WRITE_ALLOWED,
    "NUM_OF_BLOCKS_REG_RD":`SINC_NUM_OF_BLOCKS_REG_READ_ALLOWED,
    "NUM_OF_BLOCKS_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_NUM_OF_BLOCKS_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "NUM_OF_BLOCKS_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_NUM_OF_BLOCKS_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "NUM_OF_BLOCKS_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_NUM_OF_BLOCKS_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "NUM_OF_BLOCKS_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_NUM_OF_BLOCKS_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "BLOCK_ENCR_ADDR_REG_EXIST":`SINC_BLOCK_ENCR_ADDR_REG_EXIST,
    "BLOCK_ENCR_ADDR_REG_WR":`SINC_BLOCK_ENCR_ADDR_REG_WRITE_ALLOWED,
    "BLOCK_ENCR_ADDR_REG_RD":`SINC_BLOCK_ENCR_ADDR_REG_READ_ALLOWED,
    "BLOCK_ENCR_ADDR_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_BLOCK_ENCR_ADDR_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "BLOCK_ENCR_ADDR_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_BLOCK_ENCR_ADDR_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "BLOCK_ENCR_ADDR_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_BLOCK_ENCR_ADDR_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "BLOCK_ENCR_ADDR_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_BLOCK_ENCR_ADDR_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "BLOCK_ENCR_KEY_REG_EXIST":`SINC_BLOCK_ENCR_KEY_REG_EXIST,
    "BLOCK_ENCR_KEY_REG_WR":`SINC_BLOCK_ENCR_KEY_REG_WRITE_ALLOWED,
    "BLOCK_ENCR_KEY_REG_RD":`SINC_BLOCK_ENCR_KEY_REG_READ_ALLOWED,
    "BLOCK_ENCR_KEY_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_BLOCK_ENCR_KEY_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "BLOCK_ENCR_KEY_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_BLOCK_ENCR_KEY_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "BLOCK_ENCR_KEY_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_BLOCK_ENCR_KEY_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "BLOCK_ENCR_KEY_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_BLOCK_ENCR_KEY_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_IV_NONCE_0_REG_EXIST":`SINC_AES_IV_NONCE_0_REG_EXIST,
    "AES_IV_NONCE_0_REG_WR":`SINC_AES_IV_NONCE_0_REG_WRITE_ALLOWED,
    "AES_IV_NONCE_0_REG_RD":`SINC_AES_IV_NONCE_0_REG_READ_ALLOWED,
    "AES_IV_NONCE_0_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_IV_NONCE_0_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_IV_NONCE_0_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_IV_NONCE_0_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_IV_NONCE_0_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_IV_NONCE_0_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_IV_NONCE_0_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_IV_NONCE_0_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_IV_NONCE_1_REG_EXIST":`SINC_AES_IV_NONCE_1_REG_EXIST,
    "AES_IV_NONCE_1_REG_WR":`SINC_AES_IV_NONCE_1_REG_WRITE_ALLOWED,
    "AES_IV_NONCE_1_REG_RD":`SINC_AES_IV_NONCE_1_REG_READ_ALLOWED,
    "AES_IV_NONCE_1_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_IV_NONCE_1_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_IV_NONCE_1_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_IV_NONCE_1_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_IV_NONCE_1_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_IV_NONCE_1_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_IV_NONCE_1_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_IV_NONCE_1_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_IV_NONCE_2_REG_EXIST":`SINC_AES_IV_NONCE_2_REG_EXIST,
    "AES_IV_NONCE_2_REG_WR":`SINC_AES_IV_NONCE_2_REG_WRITE_ALLOWED,
    "AES_IV_NONCE_2_REG_RD":`SINC_AES_IV_NONCE_2_REG_READ_ALLOWED,
    "AES_IV_NONCE_2_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_IV_NONCE_2_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_IV_NONCE_2_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_IV_NONCE_2_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_IV_NONCE_2_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_IV_NONCE_2_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_IV_NONCE_2_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_IV_NONCE_2_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "EXT_BLOCK_BASE_ADDR_REG_EXIST":`SINC_EXT_BLOCK_BASE_ADDR_REG_EXIST,
    "EXT_BLOCK_BASE_ADDR_REG_WR":`SINC_EXT_BLOCK_BASE_ADDR_REG_WRITE_ALLOWED,
    "EXT_BLOCK_BASE_ADDR_REG_RD":`SINC_EXT_BLOCK_BASE_ADDR_REG_READ_ALLOWED,
    "EXT_BLOCK_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_EXT_BLOCK_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "EXT_BLOCK_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_EXT_BLOCK_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "EXT_BLOCK_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_EXT_BLOCK_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "EXT_BLOCK_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_EXT_BLOCK_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "EXT_AUTH_TAG_BASE_ADDR_REG_EXIST":`SINC_EXT_AUTH_TAG_BASE_ADDR_REG_EXIST,
    "EXT_AUTH_TAG_BASE_ADDR_REG_WR":`SINC_EXT_AUTH_TAG_BASE_ADDR_REG_WRITE_ALLOWED,
    "EXT_AUTH_TAG_BASE_ADDR_REG_RD":`SINC_EXT_AUTH_TAG_BASE_ADDR_REG_READ_ALLOWED,
    "EXT_AUTH_TAG_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_EXT_AUTH_TAG_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "EXT_AUTH_TAG_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_EXT_AUTH_TAG_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "EXT_AUTH_TAG_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_EXT_AUTH_TAG_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "EXT_AUTH_TAG_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_EXT_AUTH_TAG_BASE_ADDR_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "STATUS_REG_EXIST":`SINC_STATUS_REG_EXIST,
    "STATUS_REG_WR":`SINC_STATUS_REG_WRITE_ALLOWED,
    "STATUS_REG_RD":`SINC_STATUS_REG_READ_ALLOWED,
    "STATUS_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_STATUS_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "STATUS_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_STATUS_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "STATUS_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_STATUS_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "STATUS_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_STATUS_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "HIT_CNTR_LOWER_REG_EXIST":`SINC_HIT_CNTR_LOWER_REG_EXIST,
    "HIT_CNTR_LOWER_REG_WR":`SINC_HIT_CNTR_LOWER_REG_WRITE_ALLOWED,
    "HIT_CNTR_LOWER_REG_RD":`SINC_HIT_CNTR_LOWER_REG_READ_ALLOWED,
    "HIT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_HIT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "HIT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_HIT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "HIT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_HIT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "HIT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_HIT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "HIT_CNTR_UPPER_REG_EXIST":`SINC_HIT_CNTR_UPPER_REG_EXIST,
    "HIT_CNTR_UPPER_REG_WR":`SINC_HIT_CNTR_UPPER_REG_WRITE_ALLOWED,
    "HIT_CNTR_UPPER_REG_RD":`SINC_HIT_CNTR_UPPER_REG_READ_ALLOWED,
    "HIT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_HIT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "HIT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_HIT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "HIT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_HIT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "HIT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_HIT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "MISS_CNTR_LOWER_REG_EXIST":`SINC_MISS_CNTR_LOWER_REG_EXIST,
    "MISS_CNTR_LOWER_REG_WR":`SINC_MISS_CNTR_LOWER_REG_WRITE_ALLOWED,
    "MISS_CNTR_LOWER_REG_RD":`SINC_MISS_CNTR_LOWER_REG_READ_ALLOWED,
    "MISS_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_MISS_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "MISS_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_MISS_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "MISS_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_MISS_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "MISS_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_MISS_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "MISS_CNTR_UPPER_REG_EXIST":`SINC_MISS_CNTR_UPPER_REG_EXIST,
    "MISS_CNTR_UPPER_REG_WR":`SINC_MISS_CNTR_UPPER_REG_WRITE_ALLOWED,
    "MISS_CNTR_UPPER_REG_RD":`SINC_MISS_CNTR_UPPER_REG_READ_ALLOWED,
    "MISS_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_MISS_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "MISS_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_MISS_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "MISS_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_MISS_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "MISS_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_MISS_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "LAT_CNTR_LOWER_REG_EXIST":`SINC_LAT_CNTR_LOWER_REG_EXIST,
    "LAT_CNTR_LOWER_REG_WR":`SINC_LAT_CNTR_LOWER_REG_WRITE_ALLOWED,
    "LAT_CNTR_LOWER_REG_RD":`SINC_LAT_CNTR_LOWER_REG_READ_ALLOWED,
    "LAT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_LAT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "LAT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_LAT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "LAT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_LAT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "LAT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_LAT_CNTR_LOWER_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "LAT_CNTR_UPPER_REG_EXIST":`SINC_LAT_CNTR_UPPER_REG_EXIST,
    "LAT_CNTR_UPPER_REG_WR":`SINC_LAT_CNTR_UPPER_REG_WRITE_ALLOWED,
    "LAT_CNTR_UPPER_REG_RD":`SINC_LAT_CNTR_UPPER_REG_READ_ALLOWED,
    "LAT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_LAT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "LAT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_LAT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "LAT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_LAT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "LAT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_LAT_CNTR_UPPER_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "PERF_CNTR_CTRL_REG_EXIST":`SINC_PERF_CNTR_CTRL_REG_EXIST,
    "PERF_CNTR_CTRL_REG_WR":`SINC_PERF_CNTR_CTRL_REG_WRITE_ALLOWED,
    "PERF_CNTR_CTRL_REG_RD":`SINC_PERF_CNTR_CTRL_REG_READ_ALLOWED,
    "PERF_CNTR_CTRL_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_PERF_CNTR_CTRL_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "PERF_CNTR_CTRL_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_PERF_CNTR_CTRL_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "PERF_CNTR_CTRL_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_PERF_CNTR_CTRL_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "PERF_CNTR_CTRL_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_PERF_CNTR_CTRL_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_TEST_DATA_IN_0_REG_EXIST":`SINC_AES_TEST_DATA_IN_0_REG_EXIST,
    "AES_TEST_DATA_IN_0_REG_WR":`SINC_AES_TEST_DATA_IN_0_REG_WRITE_ALLOWED,
    "AES_TEST_DATA_IN_0_REG_RD":`SINC_AES_TEST_DATA_IN_0_REG_READ_ALLOWED,
    "AES_TEST_DATA_IN_0_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_TEST_DATA_IN_0_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_TEST_DATA_IN_0_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_TEST_DATA_IN_0_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_TEST_DATA_IN_0_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_TEST_DATA_IN_0_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_TEST_DATA_IN_0_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_TEST_DATA_IN_0_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_TEST_DATA_IN_1_REG_EXIST":`SINC_AES_TEST_DATA_IN_1_REG_EXIST,
    "AES_TEST_DATA_IN_1_REG_WR":`SINC_AES_TEST_DATA_IN_1_REG_WRITE_ALLOWED,
    "AES_TEST_DATA_IN_1_REG_RD":`SINC_AES_TEST_DATA_IN_1_REG_READ_ALLOWED,
    "AES_TEST_DATA_IN_1_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_TEST_DATA_IN_1_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_TEST_DATA_IN_1_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_TEST_DATA_IN_1_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_TEST_DATA_IN_1_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_TEST_DATA_IN_1_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_TEST_DATA_IN_1_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_TEST_DATA_IN_1_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_TEST_DATA_IN_2_REG_EXIST":`SINC_AES_TEST_DATA_IN_2_REG_EXIST,
    "AES_TEST_DATA_IN_2_REG_WR":`SINC_AES_TEST_DATA_IN_2_REG_WRITE_ALLOWED,
    "AES_TEST_DATA_IN_2_REG_RD":`SINC_AES_TEST_DATA_IN_2_REG_READ_ALLOWED,
    "AES_TEST_DATA_IN_2_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_TEST_DATA_IN_2_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_TEST_DATA_IN_2_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_TEST_DATA_IN_2_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_TEST_DATA_IN_2_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_TEST_DATA_IN_2_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_TEST_DATA_IN_2_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_TEST_DATA_IN_2_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_TEST_DATA_IN_3_REG_EXIST":`SINC_AES_TEST_DATA_IN_3_REG_EXIST,
    "AES_TEST_DATA_IN_3_REG_WR":`SINC_AES_TEST_DATA_IN_3_REG_WRITE_ALLOWED,
    "AES_TEST_DATA_IN_3_REG_RD":`SINC_AES_TEST_DATA_IN_3_REG_READ_ALLOWED,
    "AES_TEST_DATA_IN_3_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_TEST_DATA_IN_3_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_TEST_DATA_IN_3_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_TEST_DATA_IN_3_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_TEST_DATA_IN_3_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_TEST_DATA_IN_3_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_TEST_DATA_IN_3_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_TEST_DATA_IN_3_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_TEST_DATA_OUT_0_REG_EXIST":`SINC_AES_TEST_DATA_OUT_0_REG_EXIST,
    "AES_TEST_DATA_OUT_0_REG_WR":`SINC_AES_TEST_DATA_OUT_0_REG_WRITE_ALLOWED,
    "AES_TEST_DATA_OUT_0_REG_RD":`SINC_AES_TEST_DATA_OUT_0_REG_READ_ALLOWED,
    "AES_TEST_DATA_OUT_0_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_TEST_DATA_OUT_0_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_TEST_DATA_OUT_0_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_TEST_DATA_OUT_0_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_TEST_DATA_OUT_0_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_TEST_DATA_OUT_0_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_TEST_DATA_OUT_0_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_TEST_DATA_OUT_0_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_TEST_DATA_OUT_1_REG_EXIST":`SINC_AES_TEST_DATA_OUT_1_REG_EXIST,
    "AES_TEST_DATA_OUT_1_REG_WR":`SINC_AES_TEST_DATA_OUT_1_REG_WRITE_ALLOWED,
    "AES_TEST_DATA_OUT_1_REG_RD":`SINC_AES_TEST_DATA_OUT_1_REG_READ_ALLOWED,
    "AES_TEST_DATA_OUT_1_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_TEST_DATA_OUT_1_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_TEST_DATA_OUT_1_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_TEST_DATA_OUT_1_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_TEST_DATA_OUT_1_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_TEST_DATA_OUT_1_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_TEST_DATA_OUT_1_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_TEST_DATA_OUT_1_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_TEST_DATA_OUT_2_REG_EXIST":`SINC_AES_TEST_DATA_OUT_2_REG_EXIST,
    "AES_TEST_DATA_OUT_2_REG_WR":`SINC_AES_TEST_DATA_OUT_2_REG_WRITE_ALLOWED,
    "AES_TEST_DATA_OUT_2_REG_RD":`SINC_AES_TEST_DATA_OUT_2_REG_READ_ALLOWED,
    "AES_TEST_DATA_OUT_2_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_TEST_DATA_OUT_2_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_TEST_DATA_OUT_2_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_TEST_DATA_OUT_2_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_TEST_DATA_OUT_2_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_TEST_DATA_OUT_2_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_TEST_DATA_OUT_2_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_TEST_DATA_OUT_2_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_TEST_DATA_OUT_3_REG_EXIST":`SINC_AES_TEST_DATA_OUT_3_REG_EXIST,
    "AES_TEST_DATA_OUT_3_REG_WR":`SINC_AES_TEST_DATA_OUT_3_REG_WRITE_ALLOWED,
    "AES_TEST_DATA_OUT_3_REG_RD":`SINC_AES_TEST_DATA_OUT_3_REG_READ_ALLOWED,
    "AES_TEST_DATA_OUT_3_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_TEST_DATA_OUT_3_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_TEST_DATA_OUT_3_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_TEST_DATA_OUT_3_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_TEST_DATA_OUT_3_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_TEST_DATA_OUT_3_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_TEST_DATA_OUT_3_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_TEST_DATA_OUT_3_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_TEST_CTRL_REG_EXIST":`SINC_AES_TEST_CTRL_REG_EXIST,
    "AES_TEST_CTRL_REG_WR":`SINC_AES_TEST_CTRL_REG_WRITE_ALLOWED,
    "AES_TEST_CTRL_REG_RD":`SINC_AES_TEST_CTRL_REG_READ_ALLOWED,
    "AES_TEST_CTRL_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_TEST_CTRL_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_TEST_CTRL_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_TEST_CTRL_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_TEST_CTRL_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_TEST_CTRL_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_TEST_CTRL_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_TEST_CTRL_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "AES_TEST_STATUS_REG_EXIST":`SINC_AES_TEST_STATUS_REG_EXIST,
    "AES_TEST_STATUS_REG_WR":`SINC_AES_TEST_STATUS_REG_WRITE_ALLOWED,
    "AES_TEST_STATUS_REG_RD":`SINC_AES_TEST_STATUS_REG_READ_ALLOWED,
    "AES_TEST_STATUS_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_AES_TEST_STATUS_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "AES_TEST_STATUS_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_AES_TEST_STATUS_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "AES_TEST_STATUS_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_AES_TEST_STATUS_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "AES_TEST_STATUS_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_AES_TEST_STATUS_REG_WRITE_DISCARD_IN_CACHE_FAIL,

    "ENCR_BLOCK_STATUS_REG_EXIST":`SINC_ENCR_BLOCK_STATUS_REG_EXIST,
    "ENCR_BLOCK_STATUS_REG_WR":`SINC_ENCR_BLOCK_STATUS_REG_WRITE_ALLOWED,
    "ENCR_BLOCK_STATUS_REG_RD":`SINC_ENCR_BLOCK_STATUS_REG_READ_ALLOWED,
    "ENCR_BLOCK_STATUS_REG_WRITE_DISCARD_IN_CACHE_DISABLE":`SINC_ENCR_BLOCK_STATUS_REG_WRITE_DISCARD_IN_CACHE_DISABLE,
    "ENCR_BLOCK_STATUS_REG_WRITE_DISCARD_IN_CACHE_INIT":`SINC_ENCR_BLOCK_STATUS_REG_WRITE_DISCARD_IN_CACHE_INIT,
    "ENCR_BLOCK_STATUS_REG_WRITE_DISCARD_IN_CACHE_ACTIVE":`SINC_ENCR_BLOCK_STATUS_REG_WRITE_DISCARD_IN_CACHE_ACTIVE,
    "ENCR_BLOCK_STATUS_REG_WRITE_DISCARD_IN_CACHE_FAIL":`SINC_ENCR_BLOCK_STATUS_REG_WRITE_DISCARD_IN_CACHE_FAIL,
    default:0
  };

  /**
   * SINC Access Control Features
   */
  function static int has_feature(string name);
    return (FEATURE_NAME_HASH.exists(name));
  endfunction: has_feature

  function static int get_feature(string name);
    return (FEATURE_NAME_HASH[name]);
  endfunction: get_feature

endpackage : sinc_features_pkg

`endif // SINC_FEATURES_PKG
