// Copyright (c) Microsoft Corporation and contributors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// File         : mpu_regs.sv
// Description  : Auto-generated CSR register interface for the MPU. Provides the register
//                read/write logic for MPU status, control, and access violation registers.
//                Generated by Arteris/Semifore csrCompile.

//
// Addressmap: mpu_regs
//
//   Bus Protocol: basic
//   Bus Address Units: bytes
//
//   Access: read-write
//   Offset Units: bytes
//   Word size: 4 bytes
//
module mpu_regs (
    output wire accvio_clear,
    output wire mpu_reg_respvalid,
    output wire mpu_reg_err,
    output wire [31:0] mpu_reg_rdata,
    input  wire accvio_id_clear,
    input  wire accvio_id_load_enable,
    input  wire [3:0] accvio_id_input,
    input  wire accvio_ex_clear,
    input  wire accvio_ex_load_enable,
    input  wire accvio_ex_input,
    input  wire accvio_wr_clear,
    input  wire accvio_wr_load_enable,
    input  wire accvio_wr_input,
    input  wire accvio_rd_clear,
    input  wire accvio_rd_load_enable,
    input  wire accvio_rd_input,
    input  wire accvio_addr_clear,
    input  wire accvio_addr_load_enable,
    input  wire [23:0] accvio_addr_input,
    input  wire mpu_reg_wr_en,
    input  wire mpu_reg_rd_en,
    input  wire [7:0] mpu_reg_addr,
    input  wire [31:0] mpu_reg_wdata,
    input  wire reset_na,
    input  wire clk
    );

    // internal net declarations
    reg    csr_internal_field_mpu_status_accvio_clear;
    reg    [3:0] csr_internal_field_mpu_status_accvio_id;
    reg    csr_internal_field_mpu_status_accvio_ex;
    reg    csr_internal_field_mpu_status_accvio_wr;
    reg    csr_internal_field_mpu_status_accvio_rd;
    reg    [23:0] csr_internal_field_mpu_status_accvio_addr;

    wire   csr_internal_next_field_mpu_status_accvio_clear;
    wire   csr_internal_write_access_mpu_status_accvio_clear;
    wire   [3:0] csr_internal_next_field_mpu_status_accvio_id;
    wire   csr_internal_clear_mpu_status_accvio_id;
    wire   [3:0] csr_internal_input_mpu_status_accvio_id;
    wire   csr_internal_next_field_mpu_status_accvio_ex;
    wire   csr_internal_clear_mpu_status_accvio_ex;
    wire   csr_internal_input_mpu_status_accvio_ex;
    wire   csr_internal_next_field_mpu_status_accvio_wr;
    wire   csr_internal_clear_mpu_status_accvio_wr;
    wire   csr_internal_input_mpu_status_accvio_wr;
    wire   csr_internal_next_field_mpu_status_accvio_rd;
    wire   csr_internal_clear_mpu_status_accvio_rd;
    wire   csr_internal_input_mpu_status_accvio_rd;
    wire   [23:0] csr_internal_next_field_mpu_status_accvio_addr;
    wire   csr_internal_clear_mpu_status_accvio_addr;
    wire   [23:0] csr_internal_input_mpu_status_accvio_addr;
    wire   csr_internal_decode_mpu_status;
    wire   [31:0] csr_internal_read_value_mpu_status;
    wire   [31:0] csr_internal_read_bus_mpu_status;
    wire   csr_internal_bus_write_access;
    wire   csr_internal_bus_read_access;
    wire   csr_internal_bus_ready;
    wire   csr_internal_bus_error;
    wire   csr_internal_error;
    wire   csr_internal_valid_address;
    wire   [7:0] csr_internal_bus_address;
    wire   [31:0] csr_internal_bus_read_data;
    wire   [31:0] csr_internal_read_data;
    wire   csr_internal_read_access;
    wire   [31:0] csr_internal_bus_write_data;
    wire   csr_internal_write_access;

    //   Bus Protocol: basic
    //   Bus Address Units: bytes

    assign csr_internal_bus_address = mpu_reg_addr;
    assign csr_internal_bus_write_access = mpu_reg_wr_en;
    assign csr_internal_bus_write_data = mpu_reg_wdata;
    assign csr_internal_bus_read_access = mpu_reg_rd_en;

    assign mpu_reg_respvalid = csr_internal_bus_ready;

    assign mpu_reg_err = csr_internal_bus_error;

    assign mpu_reg_rdata = csr_internal_bus_read_data;

    assign csr_internal_read_access =
        csr_internal_bus_read_access;

    assign csr_internal_bus_read_data =
        (csr_internal_read_access) ?
            csr_internal_read_data:
            32'b0;

    assign csr_internal_write_access =
        csr_internal_bus_write_access;

    assign csr_internal_bus_ready =
        (csr_internal_bus_read_access | csr_internal_bus_write_access);

    assign csr_internal_bus_error =
        (csr_internal_bus_read_access | csr_internal_bus_write_access) &
        csr_internal_error;

    // Address Decode
    assign csr_internal_decode_mpu_status =
        (csr_internal_bus_address[7:0] == 8'h0);

    assign csr_internal_valid_address =
        csr_internal_decode_mpu_status;


    //
    // Register: mpu_status
    // Addressmap Byte Offset: 0x0
    // Access: read-write
    //
    assign csr_internal_read_value_mpu_status =
        {
            csr_internal_field_mpu_status_accvio_clear,
            csr_internal_field_mpu_status_accvio_id,
            csr_internal_field_mpu_status_accvio_ex,
            csr_internal_field_mpu_status_accvio_wr,
            csr_internal_field_mpu_status_accvio_rd,
            csr_internal_field_mpu_status_accvio_addr
        };
    assign csr_internal_read_bus_mpu_status =
        csr_internal_read_value_mpu_status &
        {32{csr_internal_decode_mpu_status}};

        // Field: mpu_status.accvio_clear
        // Position: [31]
        // Access: read-write
        // Type: configuration
        // Return To Zero
        assign csr_internal_write_access_mpu_status_accvio_clear =
            csr_internal_decode_mpu_status &
            csr_internal_write_access;

        assign csr_internal_next_field_mpu_status_accvio_clear =
            (csr_internal_write_access_mpu_status_accvio_clear) ?
                csr_internal_bus_write_data[31]:
                1'h0;

        always_ff @(posedge clk or negedge reset_na)
            if (!reset_na)
                csr_internal_field_mpu_status_accvio_clear <=
                    1'b0;
            else
                csr_internal_field_mpu_status_accvio_clear <=
                    csr_internal_next_field_mpu_status_accvio_clear;

        assign accvio_clear =
            csr_internal_field_mpu_status_accvio_clear;

        // Field: mpu_status.accvio_id
        // Position: [30:27]
        // Access: read-only
        // Type: configuration
        // Clear

        assign csr_internal_input_mpu_status_accvio_id =
            accvio_id_input;

        assign csr_internal_clear_mpu_status_accvio_id =
            accvio_id_clear;

        assign csr_internal_next_field_mpu_status_accvio_id =
            (csr_internal_clear_mpu_status_accvio_id) ?
                4'b0:
                (accvio_id_load_enable) ?
                    csr_internal_input_mpu_status_accvio_id:
                    csr_internal_field_mpu_status_accvio_id;

        always_ff @(posedge clk or negedge reset_na)
            if (!reset_na)
                csr_internal_field_mpu_status_accvio_id <=
                    4'h0;
            else
                csr_internal_field_mpu_status_accvio_id <=
                    csr_internal_next_field_mpu_status_accvio_id;

        // Field: mpu_status.accvio_ex
        // Position: [26]
        // Access: read-only
        // Type: configuration
        // Clear

        assign csr_internal_input_mpu_status_accvio_ex =
            accvio_ex_input;

        assign csr_internal_clear_mpu_status_accvio_ex =
            accvio_ex_clear;

        assign csr_internal_next_field_mpu_status_accvio_ex =
            (csr_internal_clear_mpu_status_accvio_ex) ?
                1'b0:
                (accvio_ex_load_enable) ?
                    csr_internal_input_mpu_status_accvio_ex:
                    csr_internal_field_mpu_status_accvio_ex;

        always_ff @(posedge clk or negedge reset_na)
            if (!reset_na)
                csr_internal_field_mpu_status_accvio_ex <=
                    1'h0;
            else
                csr_internal_field_mpu_status_accvio_ex <=
                    csr_internal_next_field_mpu_status_accvio_ex;

        // Field: mpu_status.accvio_wr
        // Position: [25]
        // Access: read-only
        // Type: configuration
        // Clear

        assign csr_internal_input_mpu_status_accvio_wr =
            accvio_wr_input;

        assign csr_internal_clear_mpu_status_accvio_wr =
            accvio_wr_clear;

        assign csr_internal_next_field_mpu_status_accvio_wr =
            (csr_internal_clear_mpu_status_accvio_wr) ?
                1'b0:
                (accvio_wr_load_enable) ?
                    csr_internal_input_mpu_status_accvio_wr:
                    csr_internal_field_mpu_status_accvio_wr;

        always_ff @(posedge clk or negedge reset_na)
            if (!reset_na)
                csr_internal_field_mpu_status_accvio_wr <=
                    1'h0;
            else
                csr_internal_field_mpu_status_accvio_wr <=
                    csr_internal_next_field_mpu_status_accvio_wr;

        // Field: mpu_status.accvio_rd
        // Position: [24]
        // Access: read-only
        // Type: configuration
        // Clear

        assign csr_internal_input_mpu_status_accvio_rd =
            accvio_rd_input;

        assign csr_internal_clear_mpu_status_accvio_rd =
            accvio_rd_clear;

        assign csr_internal_next_field_mpu_status_accvio_rd =
            (csr_internal_clear_mpu_status_accvio_rd) ?
                1'b0:
                (accvio_rd_load_enable) ?
                    csr_internal_input_mpu_status_accvio_rd:
                    csr_internal_field_mpu_status_accvio_rd;

        always_ff @(posedge clk or negedge reset_na)
            if (!reset_na)
                csr_internal_field_mpu_status_accvio_rd <=
                    1'h0;
            else
                csr_internal_field_mpu_status_accvio_rd <=
                    csr_internal_next_field_mpu_status_accvio_rd;

        // Field: mpu_status.accvio_addr
        // Position: [23:0]
        // Access: read-only
        // Type: configuration
        // Clear

        assign csr_internal_input_mpu_status_accvio_addr =
            accvio_addr_input;

        assign csr_internal_clear_mpu_status_accvio_addr =
            accvio_addr_clear;

        assign csr_internal_next_field_mpu_status_accvio_addr =
            (csr_internal_clear_mpu_status_accvio_addr) ?
                24'b0:
                (accvio_addr_load_enable) ?
                    csr_internal_input_mpu_status_accvio_addr:
                    csr_internal_field_mpu_status_accvio_addr;

        always_ff @(posedge clk or negedge reset_na)
            if (!reset_na)
                csr_internal_field_mpu_status_accvio_addr <=
                    24'h0;
            else
                csr_internal_field_mpu_status_accvio_addr <=
                    csr_internal_next_field_mpu_status_accvio_addr;


    assign csr_internal_read_data =
        csr_internal_read_bus_mpu_status;

    assign csr_internal_error =
        (~csr_internal_valid_address);

endmodule
