# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# File          : bom.yml
# Description   : microsoft internal compile file describing IP groups, file lists, and dependencies for open_sinc

schema_version: '1.1.0'

---
name: ip_open_sinc_rtl
requires:
  - open_sinc::ip_std_cells_rtl
  - open_sinc::ip_ram_wrapper_rtl
  - open_sinc::ip_axi_mgr_rtl
  - open_sinc::ip_axi_sub_rtl
  - open_sinc::ip_aes_engine_rtl
  - open_sinc::ip_gpaes_rtl
  - open_sinc::ip_mpu_rtl
logical_groups:
  rtl:
    incdirs:
      - ${COMPILE_ROOT}/include
    files:
      - ${COMPILE_ROOT}/rtl/sinc_regs.sv
      - ${COMPILE_ROOT}/rtl/sinc_pkg.sv
      - ${COMPILE_ROOT}/rtl/sinc_ciu.sv
      - ${COMPILE_ROOT}/rtl/sinc_ciu_ctrl.sv
      - ${COMPILE_ROOT}/rtl/sinc_ciu_vtag.sv
      - ${COMPILE_ROOT}/rtl/sinc_ciu_vtag_ret.sv
      - ${COMPILE_ROOT}/rtl/sinc_ciu_mpu_ret.sv
      - ${COMPILE_ROOT}/rtl/sinc_cmu_axi_sub_checker.sv
      - ${COMPILE_ROOT}/rtl/sinc_cmu_axi_sub_wrap.sv
      - ${COMPILE_ROOT}/rtl/sinc_cmu_reg_ctrl_ret.sv
      - ${COMPILE_ROOT}/rtl/sinc_cmu_reg_ctrl.sv
      - ${COMPILE_ROOT}/rtl/sinc_cmu_fifo.sv
      - ${COMPILE_ROOT}/rtl/sinc_cmu_ctrl_ret.sv
      - ${COMPILE_ROOT}/rtl/sinc_cmu_ctrl.sv
      - ${COMPILE_ROOT}/rtl/sinc_cmu_crypto_wrap_ctrl_ret.sv
      - ${COMPILE_ROOT}/rtl/sinc_cmu_crypto_wrap_ctrl.sv
      - ${COMPILE_ROOT}/rtl/sinc_cmu_crypto_wrap.sv
      - ${COMPILE_ROOT}/rtl/sinc_cmu_dma.sv
      - ${COMPILE_ROOT}/rtl/sinc_cmu.sv
      - ${COMPILE_ROOT}/rtl/sinc_top.sv
    tops: [sinc_top]
