/* Copyright (c) Microsoft Corporation and contributors. All rights reserved.                                      */
/*                                                                                                                 */
/* Licensed under the Apache License, Version 2.0 (the "License");                                                 */
/* you may not use this file except in compliance with the License.                                                */
/* You may obtain a copy of the License at                                                                         */
/*                                                                                                                 */
/* http://www.apache.org/licenses/LICENSE-2.0                                                                      */
/*                                                                                                                 */
/* Unless required by applicable law or agreed to in writing, software                                             */
/* distributed under the License is distributed on an "AS IS" BASIS,                                               */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.                                        */
/* See the License for the specific language governing permissions and                                            */
/* limitations under the License.                                                                                  */
/*                                                                                                                 */
/* Generated by Arteris, Inc. csrCompile                                                                           */
/*    Verilog Header output                                                                                        */

`ifndef _SINC_REGS_VH_
`define _SINC_REGS_VH_



// ##################################################################################################################
//        ADDRESS MACROS
// ##################################################################################################################

// Address Space for Addressmap: sinc_regs
// Register: sinc_regs.cmd
`define SINC_REGS_CMD_ADDRESS 10'h000
`define SINC_REGS_CMD_BYTE_ADDRESS 10'h000
// Register: sinc_regs.block_encr_num
`define SINC_REGS_BLOCK_ENCR_NUM_ADDRESS 10'h004
`define SINC_REGS_BLOCK_ENCR_NUM_BYTE_ADDRESS 10'h004
// Register: sinc_regs.num_of_blocks
`define SINC_REGS_NUM_OF_BLOCKS_ADDRESS 10'h008
`define SINC_REGS_NUM_OF_BLOCKS_BYTE_ADDRESS 10'h008
// Register: sinc_regs.block_encr_addr
`define SINC_REGS_BLOCK_ENCR_ADDR_ADDRESS 10'h00c
`define SINC_REGS_BLOCK_ENCR_ADDR_BYTE_ADDRESS 10'h00c
// Register: sinc_regs.block_encr_key
`define SINC_REGS_BLOCK_ENCR_KEY_ADDRESS 10'h010
`define SINC_REGS_BLOCK_ENCR_KEY_BYTE_ADDRESS 10'h010
// Register: sinc_regs.aes_iv_nonce_0
`define SINC_REGS_AES_IV_NONCE_0_ADDRESS 10'h014
`define SINC_REGS_AES_IV_NONCE_0_BYTE_ADDRESS 10'h014
// Register: sinc_regs.aes_iv_nonce_1
`define SINC_REGS_AES_IV_NONCE_1_ADDRESS 10'h018
`define SINC_REGS_AES_IV_NONCE_1_BYTE_ADDRESS 10'h018
// Register: sinc_regs.aes_iv_nonce_2
`define SINC_REGS_AES_IV_NONCE_2_ADDRESS 10'h01c
`define SINC_REGS_AES_IV_NONCE_2_BYTE_ADDRESS 10'h01c
// Register: sinc_regs.ext_block_base_addr
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_ADDRESS 10'h020
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_BYTE_ADDRESS 10'h020
// Register: sinc_regs.ext_auth_tag_base_addr
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_ADDRESS 10'h024
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_BYTE_ADDRESS 10'h024
// Register: sinc_regs.status
`define SINC_REGS_STATUS_ADDRESS 10'h028
`define SINC_REGS_STATUS_BYTE_ADDRESS 10'h028
// Register: sinc_regs.hit_cntr_lower
`define SINC_REGS_HIT_CNTR_LOWER_ADDRESS 10'h02c
`define SINC_REGS_HIT_CNTR_LOWER_BYTE_ADDRESS 10'h02c
// Register: sinc_regs.hit_cntr_upper
`define SINC_REGS_HIT_CNTR_UPPER_ADDRESS 10'h030
`define SINC_REGS_HIT_CNTR_UPPER_BYTE_ADDRESS 10'h030
// Register: sinc_regs.miss_cntr_lower
`define SINC_REGS_MISS_CNTR_LOWER_ADDRESS 10'h034
`define SINC_REGS_MISS_CNTR_LOWER_BYTE_ADDRESS 10'h034
// Register: sinc_regs.miss_cntr_upper
`define SINC_REGS_MISS_CNTR_UPPER_ADDRESS 10'h038
`define SINC_REGS_MISS_CNTR_UPPER_BYTE_ADDRESS 10'h038
// Register: sinc_regs.lat_cntr_lower
`define SINC_REGS_LAT_CNTR_LOWER_ADDRESS 10'h03c
`define SINC_REGS_LAT_CNTR_LOWER_BYTE_ADDRESS 10'h03c
// Register: sinc_regs.lat_cntr_upper
`define SINC_REGS_LAT_CNTR_UPPER_ADDRESS 10'h040
`define SINC_REGS_LAT_CNTR_UPPER_BYTE_ADDRESS 10'h040
// Register: sinc_regs.perf_cntr_ctrl
`define SINC_REGS_PERF_CNTR_CTRL_ADDRESS 10'h044
`define SINC_REGS_PERF_CNTR_CTRL_BYTE_ADDRESS 10'h044
// Register: sinc_regs.aes_test_data_in_0
`define SINC_REGS_AES_TEST_DATA_IN_0_ADDRESS 10'h048
`define SINC_REGS_AES_TEST_DATA_IN_0_BYTE_ADDRESS 10'h048
// Register: sinc_regs.aes_test_data_in_1
`define SINC_REGS_AES_TEST_DATA_IN_1_ADDRESS 10'h04c
`define SINC_REGS_AES_TEST_DATA_IN_1_BYTE_ADDRESS 10'h04c
// Register: sinc_regs.aes_test_data_in_2
`define SINC_REGS_AES_TEST_DATA_IN_2_ADDRESS 10'h050
`define SINC_REGS_AES_TEST_DATA_IN_2_BYTE_ADDRESS 10'h050
// Register: sinc_regs.aes_test_data_in_3
`define SINC_REGS_AES_TEST_DATA_IN_3_ADDRESS 10'h054
`define SINC_REGS_AES_TEST_DATA_IN_3_BYTE_ADDRESS 10'h054
// Register: sinc_regs.aes_test_data_out_0
`define SINC_REGS_AES_TEST_DATA_OUT_0_ADDRESS 10'h058
`define SINC_REGS_AES_TEST_DATA_OUT_0_BYTE_ADDRESS 10'h058
// Register: sinc_regs.aes_test_data_out_1
`define SINC_REGS_AES_TEST_DATA_OUT_1_ADDRESS 10'h05c
`define SINC_REGS_AES_TEST_DATA_OUT_1_BYTE_ADDRESS 10'h05c
// Register: sinc_regs.aes_test_data_out_2
`define SINC_REGS_AES_TEST_DATA_OUT_2_ADDRESS 10'h060
`define SINC_REGS_AES_TEST_DATA_OUT_2_BYTE_ADDRESS 10'h060
// Register: sinc_regs.aes_test_data_out_3
`define SINC_REGS_AES_TEST_DATA_OUT_3_ADDRESS 10'h064
`define SINC_REGS_AES_TEST_DATA_OUT_3_BYTE_ADDRESS 10'h064
// Register: sinc_regs.aes_test_ctrl
`define SINC_REGS_AES_TEST_CTRL_ADDRESS 10'h068
`define SINC_REGS_AES_TEST_CTRL_BYTE_ADDRESS 10'h068
// Register: sinc_regs.aes_test_status
`define SINC_REGS_AES_TEST_STATUS_ADDRESS 10'h06c
`define SINC_REGS_AES_TEST_STATUS_BYTE_ADDRESS 10'h06c
// Register: sinc_regs.encr_block_status
`define SINC_REGS_ENCR_BLOCK_STATUS_ADDRESS 10'h070
`define SINC_REGS_ENCR_BLOCK_STATUS_BYTE_ADDRESS 10'h070


// ##################################################################################################################
//        TEMPLATE MACROS
// ##################################################################################################################

// Addressmap type: sinc_regs
// Addressmap template: sinc_regs
`define SINC_REGS_SIZE 11'h400
`define SINC_REGS_BYTE_SIZE 11'h400
// Register member: sinc_regs.cmd
// Register type referenced: sinc_regs::cmd
// Register template referenced: sinc_regs::cmd
`define SINC_REGS_CMD_OFFSET 10'h000
`define SINC_REGS_CMD_BYTE_OFFSET 10'h000
`define SINC_REGS_CMD_READ_ACCESS 0
`define SINC_REGS_CMD_WRITE_ACCESS 1
`define SINC_REGS_CMD_RESET_VALUE 32'h00000000
`define SINC_REGS_CMD_RESET_MASK 32'hffffffff
`define SINC_REGS_CMD_READ_MASK 32'h00000000
`define SINC_REGS_CMD_WRITE_MASK 32'h000000ff
// Register member: sinc_regs.block_encr_num
// Register type referenced: sinc_regs::block_encr_num
// Register template referenced: sinc_regs::block_encr_num
`define SINC_REGS_BLOCK_ENCR_NUM_OFFSET 10'h004
`define SINC_REGS_BLOCK_ENCR_NUM_BYTE_OFFSET 10'h004
`define SINC_REGS_BLOCK_ENCR_NUM_READ_ACCESS 1
`define SINC_REGS_BLOCK_ENCR_NUM_WRITE_ACCESS 1
`define SINC_REGS_BLOCK_ENCR_NUM_RESET_VALUE 32'h00000000
`define SINC_REGS_BLOCK_ENCR_NUM_RESET_MASK 32'hffffffff
`define SINC_REGS_BLOCK_ENCR_NUM_READ_MASK 32'hffffffff
`define SINC_REGS_BLOCK_ENCR_NUM_WRITE_MASK 32'h00ffffff
// Register member: sinc_regs.num_of_blocks
// Register type referenced: sinc_regs::num_of_blocks
// Register template referenced: sinc_regs::num_of_blocks
`define SINC_REGS_NUM_OF_BLOCKS_OFFSET 10'h008
`define SINC_REGS_NUM_OF_BLOCKS_BYTE_OFFSET 10'h008
`define SINC_REGS_NUM_OF_BLOCKS_READ_ACCESS 1
`define SINC_REGS_NUM_OF_BLOCKS_WRITE_ACCESS 1
`define SINC_REGS_NUM_OF_BLOCKS_RESET_VALUE 32'h00000000
`define SINC_REGS_NUM_OF_BLOCKS_RESET_MASK 32'hffffffff
`define SINC_REGS_NUM_OF_BLOCKS_READ_MASK 32'hffffffff
`define SINC_REGS_NUM_OF_BLOCKS_WRITE_MASK 32'h00000fff
// Register member: sinc_regs.block_encr_addr
// Register type referenced: sinc_regs::block_encr_addr
// Register template referenced: sinc_regs::block_encr_addr
`define SINC_REGS_BLOCK_ENCR_ADDR_OFFSET 10'h00c
`define SINC_REGS_BLOCK_ENCR_ADDR_BYTE_OFFSET 10'h00c
`define SINC_REGS_BLOCK_ENCR_ADDR_READ_ACCESS 1
`define SINC_REGS_BLOCK_ENCR_ADDR_WRITE_ACCESS 1
`define SINC_REGS_BLOCK_ENCR_ADDR_RESET_VALUE 32'h00000000
`define SINC_REGS_BLOCK_ENCR_ADDR_RESET_MASK 32'hffffffff
`define SINC_REGS_BLOCK_ENCR_ADDR_READ_MASK 32'hffffffff
`define SINC_REGS_BLOCK_ENCR_ADDR_WRITE_MASK 32'hffffffff
// Register member: sinc_regs.block_encr_key
// Register type referenced: sinc_regs::block_encr_key
// Register template referenced: sinc_regs::block_encr_key
`define SINC_REGS_BLOCK_ENCR_KEY_OFFSET 10'h010
`define SINC_REGS_BLOCK_ENCR_KEY_BYTE_OFFSET 10'h010
`define SINC_REGS_BLOCK_ENCR_KEY_READ_ACCESS 1
`define SINC_REGS_BLOCK_ENCR_KEY_WRITE_ACCESS 1
`define SINC_REGS_BLOCK_ENCR_KEY_RESET_VALUE 32'h00000000
`define SINC_REGS_BLOCK_ENCR_KEY_RESET_MASK 32'hffffffff
`define SINC_REGS_BLOCK_ENCR_KEY_READ_MASK 32'hffffffff
`define SINC_REGS_BLOCK_ENCR_KEY_WRITE_MASK 32'h0000ffff
// Register member: sinc_regs.aes_iv_nonce_0
// Register type referenced: sinc_regs::aes_iv_nonce_0
// Register template referenced: sinc_regs::aes_iv_nonce_0
`define SINC_REGS_AES_IV_NONCE_0_OFFSET 10'h014
`define SINC_REGS_AES_IV_NONCE_0_BYTE_OFFSET 10'h014
`define SINC_REGS_AES_IV_NONCE_0_READ_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_0_WRITE_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_0_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_IV_NONCE_0_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_IV_NONCE_0_READ_MASK 32'hffffffff
`define SINC_REGS_AES_IV_NONCE_0_WRITE_MASK 32'hffffffff
// Register member: sinc_regs.aes_iv_nonce_1
// Register type referenced: sinc_regs::aes_iv_nonce_1
// Register template referenced: sinc_regs::aes_iv_nonce_1
`define SINC_REGS_AES_IV_NONCE_1_OFFSET 10'h018
`define SINC_REGS_AES_IV_NONCE_1_BYTE_OFFSET 10'h018
`define SINC_REGS_AES_IV_NONCE_1_READ_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_1_WRITE_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_1_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_IV_NONCE_1_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_IV_NONCE_1_READ_MASK 32'hffffffff
`define SINC_REGS_AES_IV_NONCE_1_WRITE_MASK 32'hffffffff
// Register member: sinc_regs.aes_iv_nonce_2
// Register type referenced: sinc_regs::aes_iv_nonce_2
// Register template referenced: sinc_regs::aes_iv_nonce_2
`define SINC_REGS_AES_IV_NONCE_2_OFFSET 10'h01c
`define SINC_REGS_AES_IV_NONCE_2_BYTE_OFFSET 10'h01c
`define SINC_REGS_AES_IV_NONCE_2_READ_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_2_WRITE_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_2_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_IV_NONCE_2_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_IV_NONCE_2_READ_MASK 32'hffffffff
`define SINC_REGS_AES_IV_NONCE_2_WRITE_MASK 32'hffffffff
// Register member: sinc_regs.ext_block_base_addr
// Register type referenced: sinc_regs::ext_block_base_addr
// Register template referenced: sinc_regs::ext_block_base_addr
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_OFFSET 10'h020
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_BYTE_OFFSET 10'h020
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_READ_ACCESS 1
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_WRITE_ACCESS 1
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_RESET_VALUE 32'h00000000
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_RESET_MASK 32'hffffffff
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_READ_MASK 32'hffffffff
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_WRITE_MASK 32'hffffffff
// Register member: sinc_regs.ext_auth_tag_base_addr
// Register type referenced: sinc_regs::ext_auth_tag_base_addr
// Register template referenced: sinc_regs::ext_auth_tag_base_addr
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_OFFSET 10'h024
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_BYTE_OFFSET 10'h024
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_READ_ACCESS 1
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_WRITE_ACCESS 1
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_RESET_VALUE 32'h00000000
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_RESET_MASK 32'hffffffff
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_READ_MASK 32'hffffffff
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_WRITE_MASK 32'hffffffff
// Register member: sinc_regs.status
// Register type referenced: sinc_regs::status
// Register template referenced: sinc_regs::status
`define SINC_REGS_STATUS_OFFSET 10'h028
`define SINC_REGS_STATUS_BYTE_OFFSET 10'h028
`define SINC_REGS_STATUS_READ_ACCESS 1
`define SINC_REGS_STATUS_WRITE_ACCESS 0
`define SINC_REGS_STATUS_RESET_VALUE 32'h00000000
`define SINC_REGS_STATUS_RESET_MASK 32'hffffffff
`define SINC_REGS_STATUS_READ_MASK 32'hffffffff
`define SINC_REGS_STATUS_WRITE_MASK 32'h00000000
// Register member: sinc_regs.hit_cntr_lower
// Register type referenced: sinc_regs::hit_cntr_lower
// Register template referenced: sinc_regs::hit_cntr_lower
`define SINC_REGS_HIT_CNTR_LOWER_OFFSET 10'h02c
`define SINC_REGS_HIT_CNTR_LOWER_BYTE_OFFSET 10'h02c
`define SINC_REGS_HIT_CNTR_LOWER_READ_ACCESS 1
`define SINC_REGS_HIT_CNTR_LOWER_WRITE_ACCESS 0
`define SINC_REGS_HIT_CNTR_LOWER_RESET_VALUE 32'h00000000
`define SINC_REGS_HIT_CNTR_LOWER_RESET_MASK 32'hffffffff
`define SINC_REGS_HIT_CNTR_LOWER_READ_MASK 32'hffffffff
`define SINC_REGS_HIT_CNTR_LOWER_WRITE_MASK 32'h00000000
// Register member: sinc_regs.hit_cntr_upper
// Register type referenced: sinc_regs::hit_cntr_upper
// Register template referenced: sinc_regs::hit_cntr_upper
`define SINC_REGS_HIT_CNTR_UPPER_OFFSET 10'h030
`define SINC_REGS_HIT_CNTR_UPPER_BYTE_OFFSET 10'h030
`define SINC_REGS_HIT_CNTR_UPPER_READ_ACCESS 1
`define SINC_REGS_HIT_CNTR_UPPER_WRITE_ACCESS 0
`define SINC_REGS_HIT_CNTR_UPPER_RESET_VALUE 32'h00000000
`define SINC_REGS_HIT_CNTR_UPPER_RESET_MASK 32'hffffffff
`define SINC_REGS_HIT_CNTR_UPPER_READ_MASK 32'hffffffff
`define SINC_REGS_HIT_CNTR_UPPER_WRITE_MASK 32'h00000000
// Register member: sinc_regs.miss_cntr_lower
// Register type referenced: sinc_regs::miss_cntr_lower
// Register template referenced: sinc_regs::miss_cntr_lower
`define SINC_REGS_MISS_CNTR_LOWER_OFFSET 10'h034
`define SINC_REGS_MISS_CNTR_LOWER_BYTE_OFFSET 10'h034
`define SINC_REGS_MISS_CNTR_LOWER_READ_ACCESS 1
`define SINC_REGS_MISS_CNTR_LOWER_WRITE_ACCESS 0
`define SINC_REGS_MISS_CNTR_LOWER_RESET_VALUE 32'h00000000
`define SINC_REGS_MISS_CNTR_LOWER_RESET_MASK 32'hffffffff
`define SINC_REGS_MISS_CNTR_LOWER_READ_MASK 32'hffffffff
`define SINC_REGS_MISS_CNTR_LOWER_WRITE_MASK 32'h00000000
// Register member: sinc_regs.miss_cntr_upper
// Register type referenced: sinc_regs::miss_cntr_upper
// Register template referenced: sinc_regs::miss_cntr_upper
`define SINC_REGS_MISS_CNTR_UPPER_OFFSET 10'h038
`define SINC_REGS_MISS_CNTR_UPPER_BYTE_OFFSET 10'h038
`define SINC_REGS_MISS_CNTR_UPPER_READ_ACCESS 1
`define SINC_REGS_MISS_CNTR_UPPER_WRITE_ACCESS 0
`define SINC_REGS_MISS_CNTR_UPPER_RESET_VALUE 32'h00000000
`define SINC_REGS_MISS_CNTR_UPPER_RESET_MASK 32'hffffffff
`define SINC_REGS_MISS_CNTR_UPPER_READ_MASK 32'hffffffff
`define SINC_REGS_MISS_CNTR_UPPER_WRITE_MASK 32'h00000000
// Register member: sinc_regs.lat_cntr_lower
// Register type referenced: sinc_regs::lat_cntr_lower
// Register template referenced: sinc_regs::lat_cntr_lower
`define SINC_REGS_LAT_CNTR_LOWER_OFFSET 10'h03c
`define SINC_REGS_LAT_CNTR_LOWER_BYTE_OFFSET 10'h03c
`define SINC_REGS_LAT_CNTR_LOWER_READ_ACCESS 1
`define SINC_REGS_LAT_CNTR_LOWER_WRITE_ACCESS 0
`define SINC_REGS_LAT_CNTR_LOWER_RESET_VALUE 32'h00000000
`define SINC_REGS_LAT_CNTR_LOWER_RESET_MASK 32'hffffffff
`define SINC_REGS_LAT_CNTR_LOWER_READ_MASK 32'hffffffff
`define SINC_REGS_LAT_CNTR_LOWER_WRITE_MASK 32'h00000000
// Register member: sinc_regs.lat_cntr_upper
// Register type referenced: sinc_regs::lat_cntr_upper
// Register template referenced: sinc_regs::lat_cntr_upper
`define SINC_REGS_LAT_CNTR_UPPER_OFFSET 10'h040
`define SINC_REGS_LAT_CNTR_UPPER_BYTE_OFFSET 10'h040
`define SINC_REGS_LAT_CNTR_UPPER_READ_ACCESS 1
`define SINC_REGS_LAT_CNTR_UPPER_WRITE_ACCESS 0
`define SINC_REGS_LAT_CNTR_UPPER_RESET_VALUE 32'h00000000
`define SINC_REGS_LAT_CNTR_UPPER_RESET_MASK 32'hffffffff
`define SINC_REGS_LAT_CNTR_UPPER_READ_MASK 32'hffffffff
`define SINC_REGS_LAT_CNTR_UPPER_WRITE_MASK 32'h00000000
// Register member: sinc_regs.perf_cntr_ctrl
// Register type referenced: sinc_regs::perf_cntr_ctrl
// Register template referenced: sinc_regs::perf_cntr_ctrl
`define SINC_REGS_PERF_CNTR_CTRL_OFFSET 10'h044
`define SINC_REGS_PERF_CNTR_CTRL_BYTE_OFFSET 10'h044
`define SINC_REGS_PERF_CNTR_CTRL_READ_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_WRITE_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_RESET_VALUE 32'h00000000
`define SINC_REGS_PERF_CNTR_CTRL_RESET_MASK 32'hffffffff
`define SINC_REGS_PERF_CNTR_CTRL_READ_MASK 32'hffffffff
`define SINC_REGS_PERF_CNTR_CTRL_WRITE_MASK 32'h0000c183
// Register member: sinc_regs.aes_test_data_in_0
// Register type referenced: sinc_regs::aes_test_data_in_0
// Register template referenced: sinc_regs::aes_test_data_in_0
`define SINC_REGS_AES_TEST_DATA_IN_0_OFFSET 10'h048
`define SINC_REGS_AES_TEST_DATA_IN_0_BYTE_OFFSET 10'h048
`define SINC_REGS_AES_TEST_DATA_IN_0_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_0_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_0_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_TEST_DATA_IN_0_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_IN_0_READ_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_IN_0_WRITE_MASK 32'hffffffff
// Register member: sinc_regs.aes_test_data_in_1
// Register type referenced: sinc_regs::aes_test_data_in_1
// Register template referenced: sinc_regs::aes_test_data_in_1
`define SINC_REGS_AES_TEST_DATA_IN_1_OFFSET 10'h04c
`define SINC_REGS_AES_TEST_DATA_IN_1_BYTE_OFFSET 10'h04c
`define SINC_REGS_AES_TEST_DATA_IN_1_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_1_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_1_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_TEST_DATA_IN_1_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_IN_1_READ_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_IN_1_WRITE_MASK 32'hffffffff
// Register member: sinc_regs.aes_test_data_in_2
// Register type referenced: sinc_regs::aes_test_data_in_2
// Register template referenced: sinc_regs::aes_test_data_in_2
`define SINC_REGS_AES_TEST_DATA_IN_2_OFFSET 10'h050
`define SINC_REGS_AES_TEST_DATA_IN_2_BYTE_OFFSET 10'h050
`define SINC_REGS_AES_TEST_DATA_IN_2_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_2_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_2_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_TEST_DATA_IN_2_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_IN_2_READ_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_IN_2_WRITE_MASK 32'hffffffff
// Register member: sinc_regs.aes_test_data_in_3
// Register type referenced: sinc_regs::aes_test_data_in_3
// Register template referenced: sinc_regs::aes_test_data_in_3
`define SINC_REGS_AES_TEST_DATA_IN_3_OFFSET 10'h054
`define SINC_REGS_AES_TEST_DATA_IN_3_BYTE_OFFSET 10'h054
`define SINC_REGS_AES_TEST_DATA_IN_3_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_3_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_3_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_TEST_DATA_IN_3_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_IN_3_READ_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_IN_3_WRITE_MASK 32'hffffffff
// Register member: sinc_regs.aes_test_data_out_0
// Register type referenced: sinc_regs::aes_test_data_out_0
// Register template referenced: sinc_regs::aes_test_data_out_0
`define SINC_REGS_AES_TEST_DATA_OUT_0_OFFSET 10'h058
`define SINC_REGS_AES_TEST_DATA_OUT_0_BYTE_OFFSET 10'h058
`define SINC_REGS_AES_TEST_DATA_OUT_0_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_OUT_0_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_DATA_OUT_0_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_TEST_DATA_OUT_0_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_OUT_0_READ_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_OUT_0_WRITE_MASK 32'h00000000
// Register member: sinc_regs.aes_test_data_out_1
// Register type referenced: sinc_regs::aes_test_data_out_1
// Register template referenced: sinc_regs::aes_test_data_out_1
`define SINC_REGS_AES_TEST_DATA_OUT_1_OFFSET 10'h05c
`define SINC_REGS_AES_TEST_DATA_OUT_1_BYTE_OFFSET 10'h05c
`define SINC_REGS_AES_TEST_DATA_OUT_1_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_OUT_1_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_DATA_OUT_1_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_TEST_DATA_OUT_1_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_OUT_1_READ_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_OUT_1_WRITE_MASK 32'h00000000
// Register member: sinc_regs.aes_test_data_out_2
// Register type referenced: sinc_regs::aes_test_data_out_2
// Register template referenced: sinc_regs::aes_test_data_out_2
`define SINC_REGS_AES_TEST_DATA_OUT_2_OFFSET 10'h060
`define SINC_REGS_AES_TEST_DATA_OUT_2_BYTE_OFFSET 10'h060
`define SINC_REGS_AES_TEST_DATA_OUT_2_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_OUT_2_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_DATA_OUT_2_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_TEST_DATA_OUT_2_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_OUT_2_READ_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_OUT_2_WRITE_MASK 32'h00000000
// Register member: sinc_regs.aes_test_data_out_3
// Register type referenced: sinc_regs::aes_test_data_out_3
// Register template referenced: sinc_regs::aes_test_data_out_3
`define SINC_REGS_AES_TEST_DATA_OUT_3_OFFSET 10'h064
`define SINC_REGS_AES_TEST_DATA_OUT_3_BYTE_OFFSET 10'h064
`define SINC_REGS_AES_TEST_DATA_OUT_3_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_OUT_3_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_DATA_OUT_3_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_TEST_DATA_OUT_3_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_OUT_3_READ_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_DATA_OUT_3_WRITE_MASK 32'h00000000
// Register member: sinc_regs.aes_test_ctrl
// Register type referenced: sinc_regs::aes_test_ctrl
// Register template referenced: sinc_regs::aes_test_ctrl
`define SINC_REGS_AES_TEST_CTRL_OFFSET 10'h068
`define SINC_REGS_AES_TEST_CTRL_BYTE_OFFSET 10'h068
`define SINC_REGS_AES_TEST_CTRL_READ_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_TEST_CTRL_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_CTRL_READ_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_CTRL_WRITE_MASK 32'h0003ffff
// Register member: sinc_regs.aes_test_status
// Register type referenced: sinc_regs::aes_test_status
// Register template referenced: sinc_regs::aes_test_status
`define SINC_REGS_AES_TEST_STATUS_OFFSET 10'h06c
`define SINC_REGS_AES_TEST_STATUS_BYTE_OFFSET 10'h06c
`define SINC_REGS_AES_TEST_STATUS_READ_ACCESS 1
`define SINC_REGS_AES_TEST_STATUS_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_STATUS_RESET_VALUE 32'h00000000
`define SINC_REGS_AES_TEST_STATUS_RESET_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_STATUS_READ_MASK 32'hffffffff
`define SINC_REGS_AES_TEST_STATUS_WRITE_MASK 32'h00000000
// Register member: sinc_regs.encr_block_status
// Register type referenced: sinc_regs::encr_block_status
// Register template referenced: sinc_regs::encr_block_status
`define SINC_REGS_ENCR_BLOCK_STATUS_OFFSET 10'h070
`define SINC_REGS_ENCR_BLOCK_STATUS_BYTE_OFFSET 10'h070
`define SINC_REGS_ENCR_BLOCK_STATUS_READ_ACCESS 1
`define SINC_REGS_ENCR_BLOCK_STATUS_WRITE_ACCESS 0
`define SINC_REGS_ENCR_BLOCK_STATUS_RESET_VALUE 32'h00000000
`define SINC_REGS_ENCR_BLOCK_STATUS_RESET_MASK 32'hffffffff
`define SINC_REGS_ENCR_BLOCK_STATUS_READ_MASK 32'hffffffff
`define SINC_REGS_ENCR_BLOCK_STATUS_WRITE_MASK 32'h00000000

// Register type: sinc_regs::cmd
// Register template: sinc_regs::cmd
`define SINC_REGS_CMD_OUTPUT_PORT_MSB 7
`define SINC_REGS_CMD_OUTPUT_PORT_LSB 0
`define SINC_REGS_CMD_OUTPUT_PORT_WIDTH 8
`define SINC_REGS_CMD_OUTPUT_PORT_RANGE 7:0
// Field member: sinc_regs::cmd.aes_test_en
`define SINC_REGS_CMD_AES_TEST_EN_MSB 7
`define SINC_REGS_CMD_AES_TEST_EN_LSB 7
`define SINC_REGS_CMD_AES_TEST_EN_WIDTH 1
`define SINC_REGS_CMD_AES_TEST_EN_RANGE 7:7
`define SINC_REGS_CMD_AES_TEST_EN_READ_ACCESS 0
`define SINC_REGS_CMD_AES_TEST_EN_WRITE_ACCESS 1
`define SINC_REGS_CMD_AES_TEST_EN_RESET 1'h0
`define SINC_REGS_CMD_AES_TEST_EN_FIELD_MASK 32'h00000080
// Field member: sinc_regs::cmd.disable_reinit
`define SINC_REGS_CMD_DISABLE_REINIT_MSB 6
`define SINC_REGS_CMD_DISABLE_REINIT_LSB 6
`define SINC_REGS_CMD_DISABLE_REINIT_WIDTH 1
`define SINC_REGS_CMD_DISABLE_REINIT_RANGE 6:6
`define SINC_REGS_CMD_DISABLE_REINIT_READ_ACCESS 0
`define SINC_REGS_CMD_DISABLE_REINIT_WRITE_ACCESS 1
`define SINC_REGS_CMD_DISABLE_REINIT_RESET 1'h0
`define SINC_REGS_CMD_DISABLE_REINIT_FIELD_MASK 32'h00000040
// Field member: sinc_regs::cmd.disable_reset
`define SINC_REGS_CMD_DISABLE_RESET_MSB 5
`define SINC_REGS_CMD_DISABLE_RESET_LSB 5
`define SINC_REGS_CMD_DISABLE_RESET_WIDTH 1
`define SINC_REGS_CMD_DISABLE_RESET_RANGE 5:5
`define SINC_REGS_CMD_DISABLE_RESET_READ_ACCESS 0
`define SINC_REGS_CMD_DISABLE_RESET_WRITE_ACCESS 1
`define SINC_REGS_CMD_DISABLE_RESET_RESET 1'h0
`define SINC_REGS_CMD_DISABLE_RESET_FIELD_MASK 32'h00000020
// Field member: sinc_regs::cmd.encr_block
`define SINC_REGS_CMD_ENCR_BLOCK_MSB 4
`define SINC_REGS_CMD_ENCR_BLOCK_LSB 4
`define SINC_REGS_CMD_ENCR_BLOCK_WIDTH 1
`define SINC_REGS_CMD_ENCR_BLOCK_RANGE 4:4
`define SINC_REGS_CMD_ENCR_BLOCK_READ_ACCESS 0
`define SINC_REGS_CMD_ENCR_BLOCK_WRITE_ACCESS 1
`define SINC_REGS_CMD_ENCR_BLOCK_RESET 1'h0
`define SINC_REGS_CMD_ENCR_BLOCK_FIELD_MASK 32'h00000010
// Field member: sinc_regs::cmd.sinc_reinit
`define SINC_REGS_CMD_SINC_REINIT_MSB 3
`define SINC_REGS_CMD_SINC_REINIT_LSB 3
`define SINC_REGS_CMD_SINC_REINIT_WIDTH 1
`define SINC_REGS_CMD_SINC_REINIT_RANGE 3:3
`define SINC_REGS_CMD_SINC_REINIT_READ_ACCESS 0
`define SINC_REGS_CMD_SINC_REINIT_WRITE_ACCESS 1
`define SINC_REGS_CMD_SINC_REINIT_RESET 1'h0
`define SINC_REGS_CMD_SINC_REINIT_FIELD_MASK 32'h00000008
// Field member: sinc_regs::cmd.sinc_reset
`define SINC_REGS_CMD_SINC_RESET_MSB 2
`define SINC_REGS_CMD_SINC_RESET_LSB 2
`define SINC_REGS_CMD_SINC_RESET_WIDTH 1
`define SINC_REGS_CMD_SINC_RESET_RANGE 2:2
`define SINC_REGS_CMD_SINC_RESET_READ_ACCESS 0
`define SINC_REGS_CMD_SINC_RESET_WRITE_ACCESS 1
`define SINC_REGS_CMD_SINC_RESET_RESET 1'h0
`define SINC_REGS_CMD_SINC_RESET_FIELD_MASK 32'h00000004
// Field member: sinc_regs::cmd.set_cache_active_state
`define SINC_REGS_CMD_SET_CACHE_ACTIVE_STATE_MSB 1
`define SINC_REGS_CMD_SET_CACHE_ACTIVE_STATE_LSB 1
`define SINC_REGS_CMD_SET_CACHE_ACTIVE_STATE_WIDTH 1
`define SINC_REGS_CMD_SET_CACHE_ACTIVE_STATE_RANGE 1:1
`define SINC_REGS_CMD_SET_CACHE_ACTIVE_STATE_READ_ACCESS 0
`define SINC_REGS_CMD_SET_CACHE_ACTIVE_STATE_WRITE_ACCESS 1
`define SINC_REGS_CMD_SET_CACHE_ACTIVE_STATE_RESET 1'h0
`define SINC_REGS_CMD_SET_CACHE_ACTIVE_STATE_FIELD_MASK 32'h00000002
// Field member: sinc_regs::cmd.set_init_state
`define SINC_REGS_CMD_SET_INIT_STATE_MSB 0
`define SINC_REGS_CMD_SET_INIT_STATE_LSB 0
`define SINC_REGS_CMD_SET_INIT_STATE_WIDTH 1
`define SINC_REGS_CMD_SET_INIT_STATE_RANGE 0:0
`define SINC_REGS_CMD_SET_INIT_STATE_READ_ACCESS 0
`define SINC_REGS_CMD_SET_INIT_STATE_WRITE_ACCESS 1
`define SINC_REGS_CMD_SET_INIT_STATE_RESET 1'h0
`define SINC_REGS_CMD_SET_INIT_STATE_FIELD_MASK 32'h00000001

// Register type: sinc_regs::block_encr_num
// Register template: sinc_regs::block_encr_num
`define SINC_REGS_BLOCK_ENCR_NUM_OUTPUT_PORT_MSB 23
`define SINC_REGS_BLOCK_ENCR_NUM_OUTPUT_PORT_LSB 0
`define SINC_REGS_BLOCK_ENCR_NUM_OUTPUT_PORT_WIDTH 24
`define SINC_REGS_BLOCK_ENCR_NUM_OUTPUT_PORT_RANGE 23:0
// Field member: sinc_regs::block_encr_num.block_encr_num
`define SINC_REGS_BLOCK_ENCR_NUM_BLOCK_ENCR_NUM_MSB 23
`define SINC_REGS_BLOCK_ENCR_NUM_BLOCK_ENCR_NUM_LSB 0
`define SINC_REGS_BLOCK_ENCR_NUM_BLOCK_ENCR_NUM_WIDTH 24
`define SINC_REGS_BLOCK_ENCR_NUM_BLOCK_ENCR_NUM_RANGE 23:0
`define SINC_REGS_BLOCK_ENCR_NUM_BLOCK_ENCR_NUM_READ_ACCESS 1
`define SINC_REGS_BLOCK_ENCR_NUM_BLOCK_ENCR_NUM_WRITE_ACCESS 1
`define SINC_REGS_BLOCK_ENCR_NUM_BLOCK_ENCR_NUM_RESET 24'h000000
`define SINC_REGS_BLOCK_ENCR_NUM_BLOCK_ENCR_NUM_FIELD_MASK 32'h00ffffff

// Register type: sinc_regs::num_of_blocks
// Register template: sinc_regs::num_of_blocks
`define SINC_REGS_NUM_OF_BLOCKS_OUTPUT_PORT_MSB 11
`define SINC_REGS_NUM_OF_BLOCKS_OUTPUT_PORT_LSB 0
`define SINC_REGS_NUM_OF_BLOCKS_OUTPUT_PORT_WIDTH 12
`define SINC_REGS_NUM_OF_BLOCKS_OUTPUT_PORT_RANGE 11:0
// Field member: sinc_regs::num_of_blocks.num_of_blocks
`define SINC_REGS_NUM_OF_BLOCKS_NUM_OF_BLOCKS_MSB 11
`define SINC_REGS_NUM_OF_BLOCKS_NUM_OF_BLOCKS_LSB 0
`define SINC_REGS_NUM_OF_BLOCKS_NUM_OF_BLOCKS_WIDTH 12
`define SINC_REGS_NUM_OF_BLOCKS_NUM_OF_BLOCKS_RANGE 11:0
`define SINC_REGS_NUM_OF_BLOCKS_NUM_OF_BLOCKS_READ_ACCESS 1
`define SINC_REGS_NUM_OF_BLOCKS_NUM_OF_BLOCKS_WRITE_ACCESS 1
`define SINC_REGS_NUM_OF_BLOCKS_NUM_OF_BLOCKS_RESET 12'h000
`define SINC_REGS_NUM_OF_BLOCKS_NUM_OF_BLOCKS_FIELD_MASK 32'h00000fff

// Register type: sinc_regs::block_encr_addr
// Register template: sinc_regs::block_encr_addr
`define SINC_REGS_BLOCK_ENCR_ADDR_OUTPUT_PORT_MSB 31
`define SINC_REGS_BLOCK_ENCR_ADDR_OUTPUT_PORT_LSB 0
`define SINC_REGS_BLOCK_ENCR_ADDR_OUTPUT_PORT_WIDTH 32
`define SINC_REGS_BLOCK_ENCR_ADDR_OUTPUT_PORT_RANGE 31:0
// Field member: sinc_regs::block_encr_addr.block_encr_addr
`define SINC_REGS_BLOCK_ENCR_ADDR_BLOCK_ENCR_ADDR_MSB 31
`define SINC_REGS_BLOCK_ENCR_ADDR_BLOCK_ENCR_ADDR_LSB 0
`define SINC_REGS_BLOCK_ENCR_ADDR_BLOCK_ENCR_ADDR_WIDTH 32
`define SINC_REGS_BLOCK_ENCR_ADDR_BLOCK_ENCR_ADDR_RANGE 31:0
`define SINC_REGS_BLOCK_ENCR_ADDR_BLOCK_ENCR_ADDR_READ_ACCESS 1
`define SINC_REGS_BLOCK_ENCR_ADDR_BLOCK_ENCR_ADDR_WRITE_ACCESS 1
`define SINC_REGS_BLOCK_ENCR_ADDR_BLOCK_ENCR_ADDR_RESET 32'h00000000
`define SINC_REGS_BLOCK_ENCR_ADDR_BLOCK_ENCR_ADDR_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::block_encr_key
// Register template: sinc_regs::block_encr_key
`define SINC_REGS_BLOCK_ENCR_KEY_OUTPUT_PORT_MSB 15
`define SINC_REGS_BLOCK_ENCR_KEY_OUTPUT_PORT_LSB 0
`define SINC_REGS_BLOCK_ENCR_KEY_OUTPUT_PORT_WIDTH 16
`define SINC_REGS_BLOCK_ENCR_KEY_OUTPUT_PORT_RANGE 15:0
// Field member: sinc_regs::block_encr_key.block_encr_key
`define SINC_REGS_BLOCK_ENCR_KEY_BLOCK_ENCR_KEY_MSB 15
`define SINC_REGS_BLOCK_ENCR_KEY_BLOCK_ENCR_KEY_LSB 0
`define SINC_REGS_BLOCK_ENCR_KEY_BLOCK_ENCR_KEY_WIDTH 16
`define SINC_REGS_BLOCK_ENCR_KEY_BLOCK_ENCR_KEY_RANGE 15:0
`define SINC_REGS_BLOCK_ENCR_KEY_BLOCK_ENCR_KEY_READ_ACCESS 1
`define SINC_REGS_BLOCK_ENCR_KEY_BLOCK_ENCR_KEY_WRITE_ACCESS 1
`define SINC_REGS_BLOCK_ENCR_KEY_BLOCK_ENCR_KEY_RESET 16'h0000
`define SINC_REGS_BLOCK_ENCR_KEY_BLOCK_ENCR_KEY_FIELD_MASK 32'h0000ffff

// Register type: sinc_regs::aes_iv_nonce_0
// Register template: sinc_regs::aes_iv_nonce_0
`define SINC_REGS_AES_IV_NONCE_0_OUTPUT_PORT_MSB 31
`define SINC_REGS_AES_IV_NONCE_0_OUTPUT_PORT_LSB 0
`define SINC_REGS_AES_IV_NONCE_0_OUTPUT_PORT_WIDTH 32
`define SINC_REGS_AES_IV_NONCE_0_OUTPUT_PORT_RANGE 31:0
// Field member: sinc_regs::aes_iv_nonce_0.aes_iv_nonce_0
`define SINC_REGS_AES_IV_NONCE_0_AES_IV_NONCE_0_MSB 31
`define SINC_REGS_AES_IV_NONCE_0_AES_IV_NONCE_0_LSB 0
`define SINC_REGS_AES_IV_NONCE_0_AES_IV_NONCE_0_WIDTH 32
`define SINC_REGS_AES_IV_NONCE_0_AES_IV_NONCE_0_RANGE 31:0
`define SINC_REGS_AES_IV_NONCE_0_AES_IV_NONCE_0_READ_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_0_AES_IV_NONCE_0_WRITE_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_0_AES_IV_NONCE_0_RESET 32'h00000000
`define SINC_REGS_AES_IV_NONCE_0_AES_IV_NONCE_0_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::aes_iv_nonce_1
// Register template: sinc_regs::aes_iv_nonce_1
`define SINC_REGS_AES_IV_NONCE_1_OUTPUT_PORT_MSB 31
`define SINC_REGS_AES_IV_NONCE_1_OUTPUT_PORT_LSB 0
`define SINC_REGS_AES_IV_NONCE_1_OUTPUT_PORT_WIDTH 32
`define SINC_REGS_AES_IV_NONCE_1_OUTPUT_PORT_RANGE 31:0
// Field member: sinc_regs::aes_iv_nonce_1.aes_iv_nonce_1
`define SINC_REGS_AES_IV_NONCE_1_AES_IV_NONCE_1_MSB 31
`define SINC_REGS_AES_IV_NONCE_1_AES_IV_NONCE_1_LSB 0
`define SINC_REGS_AES_IV_NONCE_1_AES_IV_NONCE_1_WIDTH 32
`define SINC_REGS_AES_IV_NONCE_1_AES_IV_NONCE_1_RANGE 31:0
`define SINC_REGS_AES_IV_NONCE_1_AES_IV_NONCE_1_READ_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_1_AES_IV_NONCE_1_WRITE_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_1_AES_IV_NONCE_1_RESET 32'h00000000
`define SINC_REGS_AES_IV_NONCE_1_AES_IV_NONCE_1_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::aes_iv_nonce_2
// Register template: sinc_regs::aes_iv_nonce_2
`define SINC_REGS_AES_IV_NONCE_2_OUTPUT_PORT_MSB 31
`define SINC_REGS_AES_IV_NONCE_2_OUTPUT_PORT_LSB 0
`define SINC_REGS_AES_IV_NONCE_2_OUTPUT_PORT_WIDTH 32
`define SINC_REGS_AES_IV_NONCE_2_OUTPUT_PORT_RANGE 31:0
// Field member: sinc_regs::aes_iv_nonce_2.aes_iv_nonce_2_test
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_TEST_MSB 31
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_TEST_LSB 8
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_TEST_WIDTH 24
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_TEST_RANGE 31:8
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_TEST_READ_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_TEST_WRITE_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_TEST_RESET 24'h000000
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_TEST_FIELD_MASK 32'hffffff00
// Field member: sinc_regs::aes_iv_nonce_2.aes_iv_nonce_2
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_MSB 7
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_LSB 0
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_WIDTH 8
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_RANGE 7:0
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_READ_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_WRITE_ACCESS 1
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_RESET 8'h00
`define SINC_REGS_AES_IV_NONCE_2_AES_IV_NONCE_2_FIELD_MASK 32'h000000ff

// Register type: sinc_regs::ext_block_base_addr
// Register template: sinc_regs::ext_block_base_addr
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_OUTPUT_PORT_MSB 31
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_OUTPUT_PORT_LSB 0
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_OUTPUT_PORT_WIDTH 32
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_OUTPUT_PORT_RANGE 31:0
// Field member: sinc_regs::ext_block_base_addr.ext_block_base_addr
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_EXT_BLOCK_BASE_ADDR_MSB 31
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_EXT_BLOCK_BASE_ADDR_LSB 0
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_EXT_BLOCK_BASE_ADDR_WIDTH 32
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_EXT_BLOCK_BASE_ADDR_RANGE 31:0
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_EXT_BLOCK_BASE_ADDR_READ_ACCESS 1
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_EXT_BLOCK_BASE_ADDR_WRITE_ACCESS 1
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_EXT_BLOCK_BASE_ADDR_RESET 32'h00000000
`define SINC_REGS_EXT_BLOCK_BASE_ADDR_EXT_BLOCK_BASE_ADDR_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::ext_auth_tag_base_addr
// Register template: sinc_regs::ext_auth_tag_base_addr
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_OUTPUT_PORT_MSB 31
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_OUTPUT_PORT_LSB 0
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_OUTPUT_PORT_WIDTH 32
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_OUTPUT_PORT_RANGE 31:0
// Field member: sinc_regs::ext_auth_tag_base_addr.ext_auth_tag_base_addr
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_EXT_AUTH_TAG_BASE_ADDR_MSB 31
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_EXT_AUTH_TAG_BASE_ADDR_LSB 0
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_EXT_AUTH_TAG_BASE_ADDR_WIDTH 32
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_EXT_AUTH_TAG_BASE_ADDR_RANGE 31:0
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_EXT_AUTH_TAG_BASE_ADDR_READ_ACCESS 1
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_EXT_AUTH_TAG_BASE_ADDR_WRITE_ACCESS 1
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_EXT_AUTH_TAG_BASE_ADDR_RESET 32'h00000000
`define SINC_REGS_EXT_AUTH_TAG_BASE_ADDR_EXT_AUTH_TAG_BASE_ADDR_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::status
// Register template: sinc_regs::status
`define SINC_REGS_STATUS_OUTPUT_PORT_MSB 23
`define SINC_REGS_STATUS_OUTPUT_PORT_LSB 0
`define SINC_REGS_STATUS_OUTPUT_PORT_WIDTH 24
`define SINC_REGS_STATUS_OUTPUT_PORT_RANGE 23:0
// Field member: sinc_regs::status.sinc_hw_fault
`define SINC_REGS_STATUS_SINC_HW_FAULT_MSB 23
`define SINC_REGS_STATUS_SINC_HW_FAULT_LSB 23
`define SINC_REGS_STATUS_SINC_HW_FAULT_WIDTH 1
`define SINC_REGS_STATUS_SINC_HW_FAULT_RANGE 23:23
`define SINC_REGS_STATUS_SINC_HW_FAULT_READ_ACCESS 1
`define SINC_REGS_STATUS_SINC_HW_FAULT_WRITE_ACCESS 0
`define SINC_REGS_STATUS_SINC_HW_FAULT_RESET 1'h0
`define SINC_REGS_STATUS_SINC_HW_FAULT_FIELD_MASK 32'h00800000
// Field member: sinc_regs::status.aes_err
`define SINC_REGS_STATUS_AES_ERR_MSB 22
`define SINC_REGS_STATUS_AES_ERR_LSB 22
`define SINC_REGS_STATUS_AES_ERR_WIDTH 1
`define SINC_REGS_STATUS_AES_ERR_RANGE 22:22
`define SINC_REGS_STATUS_AES_ERR_READ_ACCESS 1
`define SINC_REGS_STATUS_AES_ERR_WRITE_ACCESS 0
`define SINC_REGS_STATUS_AES_ERR_RESET 1'h0
`define SINC_REGS_STATUS_AES_ERR_FIELD_MASK 32'h00400000
// Field member: sinc_regs::status.auth_tag_w_err
`define SINC_REGS_STATUS_AUTH_TAG_W_ERR_MSB 21
`define SINC_REGS_STATUS_AUTH_TAG_W_ERR_LSB 21
`define SINC_REGS_STATUS_AUTH_TAG_W_ERR_WIDTH 1
`define SINC_REGS_STATUS_AUTH_TAG_W_ERR_RANGE 21:21
`define SINC_REGS_STATUS_AUTH_TAG_W_ERR_READ_ACCESS 1
`define SINC_REGS_STATUS_AUTH_TAG_W_ERR_WRITE_ACCESS 0
`define SINC_REGS_STATUS_AUTH_TAG_W_ERR_RESET 1'h0
`define SINC_REGS_STATUS_AUTH_TAG_W_ERR_FIELD_MASK 32'h00200000
// Field member: sinc_regs::status.auth_tag_chk_err
`define SINC_REGS_STATUS_AUTH_TAG_CHK_ERR_MSB 20
`define SINC_REGS_STATUS_AUTH_TAG_CHK_ERR_LSB 20
`define SINC_REGS_STATUS_AUTH_TAG_CHK_ERR_WIDTH 1
`define SINC_REGS_STATUS_AUTH_TAG_CHK_ERR_RANGE 20:20
`define SINC_REGS_STATUS_AUTH_TAG_CHK_ERR_READ_ACCESS 1
`define SINC_REGS_STATUS_AUTH_TAG_CHK_ERR_WRITE_ACCESS 0
`define SINC_REGS_STATUS_AUTH_TAG_CHK_ERR_RESET 1'h0
`define SINC_REGS_STATUS_AUTH_TAG_CHK_ERR_FIELD_MASK 32'h00100000
// Field member: sinc_regs::status.auth_tag_r_err
`define SINC_REGS_STATUS_AUTH_TAG_R_ERR_MSB 19
`define SINC_REGS_STATUS_AUTH_TAG_R_ERR_LSB 19
`define SINC_REGS_STATUS_AUTH_TAG_R_ERR_WIDTH 1
`define SINC_REGS_STATUS_AUTH_TAG_R_ERR_RANGE 19:19
`define SINC_REGS_STATUS_AUTH_TAG_R_ERR_READ_ACCESS 1
`define SINC_REGS_STATUS_AUTH_TAG_R_ERR_WRITE_ACCESS 0
`define SINC_REGS_STATUS_AUTH_TAG_R_ERR_RESET 1'h0
`define SINC_REGS_STATUS_AUTH_TAG_R_ERR_FIELD_MASK 32'h00080000
// Field member: sinc_regs::status.cache_block_w_err_fetch_block
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_FETCH_BLOCK_MSB 18
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_FETCH_BLOCK_LSB 18
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_FETCH_BLOCK_WIDTH 1
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_FETCH_BLOCK_RANGE 18:18
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_FETCH_BLOCK_READ_ACCESS 1
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_FETCH_BLOCK_WRITE_ACCESS 0
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_FETCH_BLOCK_RESET 1'h0
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_FETCH_BLOCK_FIELD_MASK 32'h00040000
// Field member: sinc_regs::status.cache_block_w_err_encr_block
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_ENCR_BLOCK_MSB 17
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_ENCR_BLOCK_LSB 17
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_ENCR_BLOCK_WIDTH 1
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_ENCR_BLOCK_RANGE 17:17
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_ENCR_BLOCK_READ_ACCESS 1
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_ENCR_BLOCK_WRITE_ACCESS 0
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_ENCR_BLOCK_RESET 1'h0
`define SINC_REGS_STATUS_CACHE_BLOCK_W_ERR_ENCR_BLOCK_FIELD_MASK 32'h00020000
// Field member: sinc_regs::status.cache_block_r_err
`define SINC_REGS_STATUS_CACHE_BLOCK_R_ERR_MSB 16
`define SINC_REGS_STATUS_CACHE_BLOCK_R_ERR_LSB 16
`define SINC_REGS_STATUS_CACHE_BLOCK_R_ERR_WIDTH 1
`define SINC_REGS_STATUS_CACHE_BLOCK_R_ERR_RANGE 16:16
`define SINC_REGS_STATUS_CACHE_BLOCK_R_ERR_READ_ACCESS 1
`define SINC_REGS_STATUS_CACHE_BLOCK_R_ERR_WRITE_ACCESS 0
`define SINC_REGS_STATUS_CACHE_BLOCK_R_ERR_RESET 1'h0
`define SINC_REGS_STATUS_CACHE_BLOCK_R_ERR_FIELD_MASK 32'h00010000
// Field member: sinc_regs::status.key_fetch_err
`define SINC_REGS_STATUS_KEY_FETCH_ERR_MSB 15
`define SINC_REGS_STATUS_KEY_FETCH_ERR_LSB 15
`define SINC_REGS_STATUS_KEY_FETCH_ERR_WIDTH 1
`define SINC_REGS_STATUS_KEY_FETCH_ERR_RANGE 15:15
`define SINC_REGS_STATUS_KEY_FETCH_ERR_READ_ACCESS 1
`define SINC_REGS_STATUS_KEY_FETCH_ERR_WRITE_ACCESS 0
`define SINC_REGS_STATUS_KEY_FETCH_ERR_RESET 1'h0
`define SINC_REGS_STATUS_KEY_FETCH_ERR_FIELD_MASK 32'h00008000
// Field member: sinc_regs::status.rng_seed_r_err
`define SINC_REGS_STATUS_RNG_SEED_R_ERR_MSB 14
`define SINC_REGS_STATUS_RNG_SEED_R_ERR_LSB 14
`define SINC_REGS_STATUS_RNG_SEED_R_ERR_WIDTH 1
`define SINC_REGS_STATUS_RNG_SEED_R_ERR_RANGE 14:14
`define SINC_REGS_STATUS_RNG_SEED_R_ERR_READ_ACCESS 1
`define SINC_REGS_STATUS_RNG_SEED_R_ERR_WRITE_ACCESS 0
`define SINC_REGS_STATUS_RNG_SEED_R_ERR_RESET 1'h0
`define SINC_REGS_STATUS_RNG_SEED_R_ERR_FIELD_MASK 32'h00004000
// Field member: sinc_regs::status.invalid_cmd_err
`define SINC_REGS_STATUS_INVALID_CMD_ERR_MSB 13
`define SINC_REGS_STATUS_INVALID_CMD_ERR_LSB 13
`define SINC_REGS_STATUS_INVALID_CMD_ERR_WIDTH 1
`define SINC_REGS_STATUS_INVALID_CMD_ERR_RANGE 13:13
`define SINC_REGS_STATUS_INVALID_CMD_ERR_READ_ACCESS 1
`define SINC_REGS_STATUS_INVALID_CMD_ERR_WRITE_ACCESS 0
`define SINC_REGS_STATUS_INVALID_CMD_ERR_RESET 1'h0
`define SINC_REGS_STATUS_INVALID_CMD_ERR_FIELD_MASK 32'h00002000
// Field member: sinc_regs::status.cmd_failed
`define SINC_REGS_STATUS_CMD_FAILED_MSB 12
`define SINC_REGS_STATUS_CMD_FAILED_LSB 12
`define SINC_REGS_STATUS_CMD_FAILED_WIDTH 1
`define SINC_REGS_STATUS_CMD_FAILED_RANGE 12:12
`define SINC_REGS_STATUS_CMD_FAILED_READ_ACCESS 1
`define SINC_REGS_STATUS_CMD_FAILED_WRITE_ACCESS 0
`define SINC_REGS_STATUS_CMD_FAILED_RESET 1'h0
`define SINC_REGS_STATUS_CMD_FAILED_FIELD_MASK 32'h00001000
// Field member: sinc_regs::status.cmd_success
`define SINC_REGS_STATUS_CMD_SUCCESS_MSB 11
`define SINC_REGS_STATUS_CMD_SUCCESS_LSB 11
`define SINC_REGS_STATUS_CMD_SUCCESS_WIDTH 1
`define SINC_REGS_STATUS_CMD_SUCCESS_RANGE 11:11
`define SINC_REGS_STATUS_CMD_SUCCESS_READ_ACCESS 1
`define SINC_REGS_STATUS_CMD_SUCCESS_WRITE_ACCESS 0
`define SINC_REGS_STATUS_CMD_SUCCESS_RESET 1'h0
`define SINC_REGS_STATUS_CMD_SUCCESS_FIELD_MASK 32'h00000800
// Field member: sinc_regs::status.cmd_in_progress
`define SINC_REGS_STATUS_CMD_IN_PROGRESS_MSB 10
`define SINC_REGS_STATUS_CMD_IN_PROGRESS_LSB 10
`define SINC_REGS_STATUS_CMD_IN_PROGRESS_WIDTH 1
`define SINC_REGS_STATUS_CMD_IN_PROGRESS_RANGE 10:10
`define SINC_REGS_STATUS_CMD_IN_PROGRESS_READ_ACCESS 1
`define SINC_REGS_STATUS_CMD_IN_PROGRESS_WRITE_ACCESS 0
`define SINC_REGS_STATUS_CMD_IN_PROGRESS_RESET 1'h0
`define SINC_REGS_STATUS_CMD_IN_PROGRESS_FIELD_MASK 32'h00000400
// Field member: sinc_regs::status.sinc_reinit_disabled
`define SINC_REGS_STATUS_SINC_REINIT_DISABLED_MSB 9
`define SINC_REGS_STATUS_SINC_REINIT_DISABLED_LSB 9
`define SINC_REGS_STATUS_SINC_REINIT_DISABLED_WIDTH 1
`define SINC_REGS_STATUS_SINC_REINIT_DISABLED_RANGE 9:9
`define SINC_REGS_STATUS_SINC_REINIT_DISABLED_READ_ACCESS 1
`define SINC_REGS_STATUS_SINC_REINIT_DISABLED_WRITE_ACCESS 0
`define SINC_REGS_STATUS_SINC_REINIT_DISABLED_RESET 1'b0
`define SINC_REGS_STATUS_SINC_REINIT_DISABLED_FIELD_MASK 32'h00000200
// Field member: sinc_regs::status.sinc_reset_disabled
`define SINC_REGS_STATUS_SINC_RESET_DISABLED_MSB 8
`define SINC_REGS_STATUS_SINC_RESET_DISABLED_LSB 8
`define SINC_REGS_STATUS_SINC_RESET_DISABLED_WIDTH 1
`define SINC_REGS_STATUS_SINC_RESET_DISABLED_RANGE 8:8
`define SINC_REGS_STATUS_SINC_RESET_DISABLED_READ_ACCESS 1
`define SINC_REGS_STATUS_SINC_RESET_DISABLED_WRITE_ACCESS 0
`define SINC_REGS_STATUS_SINC_RESET_DISABLED_RESET 1'b0
`define SINC_REGS_STATUS_SINC_RESET_DISABLED_FIELD_MASK 32'h00000100
// Field member: sinc_regs::status.state
`define SINC_REGS_STATUS_STATE_MSB 7
`define SINC_REGS_STATUS_STATE_LSB 0
`define SINC_REGS_STATUS_STATE_WIDTH 8
`define SINC_REGS_STATUS_STATE_RANGE 7:0
`define SINC_REGS_STATUS_STATE_READ_ACCESS 1
`define SINC_REGS_STATUS_STATE_WRITE_ACCESS 0
`define SINC_REGS_STATUS_STATE_RESET 8'h00
`define SINC_REGS_STATUS_STATE_FIELD_MASK 32'h000000ff

// Register type: sinc_regs::hit_cntr_lower
// Register template: sinc_regs::hit_cntr_lower
// Field member: sinc_regs::hit_cntr_lower.hit_cntr_lower
`define SINC_REGS_HIT_CNTR_LOWER_HIT_CNTR_LOWER_MSB 31
`define SINC_REGS_HIT_CNTR_LOWER_HIT_CNTR_LOWER_LSB 0
`define SINC_REGS_HIT_CNTR_LOWER_HIT_CNTR_LOWER_WIDTH 32
`define SINC_REGS_HIT_CNTR_LOWER_HIT_CNTR_LOWER_RANGE 31:0
`define SINC_REGS_HIT_CNTR_LOWER_HIT_CNTR_LOWER_READ_ACCESS 1
`define SINC_REGS_HIT_CNTR_LOWER_HIT_CNTR_LOWER_WRITE_ACCESS 0
`define SINC_REGS_HIT_CNTR_LOWER_HIT_CNTR_LOWER_RESET 32'h00000000
`define SINC_REGS_HIT_CNTR_LOWER_HIT_CNTR_LOWER_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::hit_cntr_upper
// Register template: sinc_regs::hit_cntr_upper
// Field member: sinc_regs::hit_cntr_upper.hit_cntr_upper
`define SINC_REGS_HIT_CNTR_UPPER_HIT_CNTR_UPPER_MSB 15
`define SINC_REGS_HIT_CNTR_UPPER_HIT_CNTR_UPPER_LSB 0
`define SINC_REGS_HIT_CNTR_UPPER_HIT_CNTR_UPPER_WIDTH 16
`define SINC_REGS_HIT_CNTR_UPPER_HIT_CNTR_UPPER_RANGE 15:0
`define SINC_REGS_HIT_CNTR_UPPER_HIT_CNTR_UPPER_READ_ACCESS 1
`define SINC_REGS_HIT_CNTR_UPPER_HIT_CNTR_UPPER_WRITE_ACCESS 0
`define SINC_REGS_HIT_CNTR_UPPER_HIT_CNTR_UPPER_RESET 16'h0000
`define SINC_REGS_HIT_CNTR_UPPER_HIT_CNTR_UPPER_FIELD_MASK 32'h0000ffff

// Register type: sinc_regs::miss_cntr_lower
// Register template: sinc_regs::miss_cntr_lower
// Field member: sinc_regs::miss_cntr_lower.miss_cntr_lower
`define SINC_REGS_MISS_CNTR_LOWER_MISS_CNTR_LOWER_MSB 31
`define SINC_REGS_MISS_CNTR_LOWER_MISS_CNTR_LOWER_LSB 0
`define SINC_REGS_MISS_CNTR_LOWER_MISS_CNTR_LOWER_WIDTH 32
`define SINC_REGS_MISS_CNTR_LOWER_MISS_CNTR_LOWER_RANGE 31:0
`define SINC_REGS_MISS_CNTR_LOWER_MISS_CNTR_LOWER_READ_ACCESS 1
`define SINC_REGS_MISS_CNTR_LOWER_MISS_CNTR_LOWER_WRITE_ACCESS 0
`define SINC_REGS_MISS_CNTR_LOWER_MISS_CNTR_LOWER_RESET 32'h00000000
`define SINC_REGS_MISS_CNTR_LOWER_MISS_CNTR_LOWER_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::miss_cntr_upper
// Register template: sinc_regs::miss_cntr_upper
// Field member: sinc_regs::miss_cntr_upper.miss_cntr_upper
`define SINC_REGS_MISS_CNTR_UPPER_MISS_CNTR_UPPER_MSB 15
`define SINC_REGS_MISS_CNTR_UPPER_MISS_CNTR_UPPER_LSB 0
`define SINC_REGS_MISS_CNTR_UPPER_MISS_CNTR_UPPER_WIDTH 16
`define SINC_REGS_MISS_CNTR_UPPER_MISS_CNTR_UPPER_RANGE 15:0
`define SINC_REGS_MISS_CNTR_UPPER_MISS_CNTR_UPPER_READ_ACCESS 1
`define SINC_REGS_MISS_CNTR_UPPER_MISS_CNTR_UPPER_WRITE_ACCESS 0
`define SINC_REGS_MISS_CNTR_UPPER_MISS_CNTR_UPPER_RESET 16'h0000
`define SINC_REGS_MISS_CNTR_UPPER_MISS_CNTR_UPPER_FIELD_MASK 32'h0000ffff

// Register type: sinc_regs::lat_cntr_lower
// Register template: sinc_regs::lat_cntr_lower
// Field member: sinc_regs::lat_cntr_lower.lat_cntr_lower
`define SINC_REGS_LAT_CNTR_LOWER_LAT_CNTR_LOWER_MSB 31
`define SINC_REGS_LAT_CNTR_LOWER_LAT_CNTR_LOWER_LSB 0
`define SINC_REGS_LAT_CNTR_LOWER_LAT_CNTR_LOWER_WIDTH 32
`define SINC_REGS_LAT_CNTR_LOWER_LAT_CNTR_LOWER_RANGE 31:0
`define SINC_REGS_LAT_CNTR_LOWER_LAT_CNTR_LOWER_READ_ACCESS 1
`define SINC_REGS_LAT_CNTR_LOWER_LAT_CNTR_LOWER_WRITE_ACCESS 0
`define SINC_REGS_LAT_CNTR_LOWER_LAT_CNTR_LOWER_RESET 32'h00000000
`define SINC_REGS_LAT_CNTR_LOWER_LAT_CNTR_LOWER_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::lat_cntr_upper
// Register template: sinc_regs::lat_cntr_upper
// Field member: sinc_regs::lat_cntr_upper.lat_cntr_upper
`define SINC_REGS_LAT_CNTR_UPPER_LAT_CNTR_UPPER_MSB 15
`define SINC_REGS_LAT_CNTR_UPPER_LAT_CNTR_UPPER_LSB 0
`define SINC_REGS_LAT_CNTR_UPPER_LAT_CNTR_UPPER_WIDTH 16
`define SINC_REGS_LAT_CNTR_UPPER_LAT_CNTR_UPPER_RANGE 15:0
`define SINC_REGS_LAT_CNTR_UPPER_LAT_CNTR_UPPER_READ_ACCESS 1
`define SINC_REGS_LAT_CNTR_UPPER_LAT_CNTR_UPPER_WRITE_ACCESS 0
`define SINC_REGS_LAT_CNTR_UPPER_LAT_CNTR_UPPER_RESET 16'h0000
`define SINC_REGS_LAT_CNTR_UPPER_LAT_CNTR_UPPER_FIELD_MASK 32'h0000ffff

// Register type: sinc_regs::perf_cntr_ctrl
// Register template: sinc_regs::perf_cntr_ctrl
`define SINC_REGS_PERF_CNTR_CTRL_OUTPUT_PORT_MSB 15
`define SINC_REGS_PERF_CNTR_CTRL_OUTPUT_PORT_LSB 0
`define SINC_REGS_PERF_CNTR_CTRL_OUTPUT_PORT_WIDTH 16
`define SINC_REGS_PERF_CNTR_CTRL_OUTPUT_PORT_RANGE 15:0
// Field member: sinc_regs::perf_cntr_ctrl.lat_cntr_clr
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_CLR_MSB 15
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_CLR_LSB 15
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_CLR_WIDTH 1
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_CLR_RANGE 15:15
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_CLR_READ_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_CLR_WRITE_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_CLR_RESET 1'h0
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_CLR_FIELD_MASK 32'h00008000
// Field member: sinc_regs::perf_cntr_ctrl.lat_cntr_en
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_EN_MSB 14
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_EN_LSB 14
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_EN_WIDTH 1
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_EN_RANGE 14:14
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_EN_READ_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_EN_WRITE_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_EN_RESET 1'h0
`define SINC_REGS_PERF_CNTR_CTRL_LAT_CNTR_EN_FIELD_MASK 32'h00004000
// Field member: sinc_regs::perf_cntr_ctrl.miss_cntr_clr
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_CLR_MSB 8
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_CLR_LSB 8
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_CLR_WIDTH 1
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_CLR_RANGE 8:8
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_CLR_READ_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_CLR_WRITE_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_CLR_RESET 1'h0
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_CLR_FIELD_MASK 32'h00000100
// Field member: sinc_regs::perf_cntr_ctrl.miss_cntr_en
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_EN_MSB 7
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_EN_LSB 7
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_EN_WIDTH 1
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_EN_RANGE 7:7
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_EN_READ_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_EN_WRITE_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_EN_RESET 1'h0
`define SINC_REGS_PERF_CNTR_CTRL_MISS_CNTR_EN_FIELD_MASK 32'h00000080
// Field member: sinc_regs::perf_cntr_ctrl.hit_cntr_clr
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_CLR_MSB 1
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_CLR_LSB 1
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_CLR_WIDTH 1
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_CLR_RANGE 1:1
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_CLR_READ_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_CLR_WRITE_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_CLR_RESET 1'h0
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_CLR_FIELD_MASK 32'h00000002
// Field member: sinc_regs::perf_cntr_ctrl.hit_cntr_en
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_EN_MSB 0
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_EN_LSB 0
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_EN_WIDTH 1
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_EN_RANGE 0:0
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_EN_READ_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_EN_WRITE_ACCESS 1
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_EN_RESET 1'h0
`define SINC_REGS_PERF_CNTR_CTRL_HIT_CNTR_EN_FIELD_MASK 32'h00000001

// Register type: sinc_regs::aes_test_data_in_0
// Register template: sinc_regs::aes_test_data_in_0
`define SINC_REGS_AES_TEST_DATA_IN_0_OUTPUT_PORT_MSB 31
`define SINC_REGS_AES_TEST_DATA_IN_0_OUTPUT_PORT_LSB 0
`define SINC_REGS_AES_TEST_DATA_IN_0_OUTPUT_PORT_WIDTH 32
`define SINC_REGS_AES_TEST_DATA_IN_0_OUTPUT_PORT_RANGE 31:0
// Field member: sinc_regs::aes_test_data_in_0.aes_test_data_in_0
`define SINC_REGS_AES_TEST_DATA_IN_0_AES_TEST_DATA_IN_0_MSB 31
`define SINC_REGS_AES_TEST_DATA_IN_0_AES_TEST_DATA_IN_0_LSB 0
`define SINC_REGS_AES_TEST_DATA_IN_0_AES_TEST_DATA_IN_0_WIDTH 32
`define SINC_REGS_AES_TEST_DATA_IN_0_AES_TEST_DATA_IN_0_RANGE 31:0
`define SINC_REGS_AES_TEST_DATA_IN_0_AES_TEST_DATA_IN_0_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_0_AES_TEST_DATA_IN_0_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_0_AES_TEST_DATA_IN_0_RESET 32'h00000000
`define SINC_REGS_AES_TEST_DATA_IN_0_AES_TEST_DATA_IN_0_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::aes_test_data_in_1
// Register template: sinc_regs::aes_test_data_in_1
`define SINC_REGS_AES_TEST_DATA_IN_1_OUTPUT_PORT_MSB 31
`define SINC_REGS_AES_TEST_DATA_IN_1_OUTPUT_PORT_LSB 0
`define SINC_REGS_AES_TEST_DATA_IN_1_OUTPUT_PORT_WIDTH 32
`define SINC_REGS_AES_TEST_DATA_IN_1_OUTPUT_PORT_RANGE 31:0
// Field member: sinc_regs::aes_test_data_in_1.aes_test_data_in_1
`define SINC_REGS_AES_TEST_DATA_IN_1_AES_TEST_DATA_IN_1_MSB 31
`define SINC_REGS_AES_TEST_DATA_IN_1_AES_TEST_DATA_IN_1_LSB 0
`define SINC_REGS_AES_TEST_DATA_IN_1_AES_TEST_DATA_IN_1_WIDTH 32
`define SINC_REGS_AES_TEST_DATA_IN_1_AES_TEST_DATA_IN_1_RANGE 31:0
`define SINC_REGS_AES_TEST_DATA_IN_1_AES_TEST_DATA_IN_1_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_1_AES_TEST_DATA_IN_1_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_1_AES_TEST_DATA_IN_1_RESET 32'h00000000
`define SINC_REGS_AES_TEST_DATA_IN_1_AES_TEST_DATA_IN_1_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::aes_test_data_in_2
// Register template: sinc_regs::aes_test_data_in_2
`define SINC_REGS_AES_TEST_DATA_IN_2_OUTPUT_PORT_MSB 31
`define SINC_REGS_AES_TEST_DATA_IN_2_OUTPUT_PORT_LSB 0
`define SINC_REGS_AES_TEST_DATA_IN_2_OUTPUT_PORT_WIDTH 32
`define SINC_REGS_AES_TEST_DATA_IN_2_OUTPUT_PORT_RANGE 31:0
// Field member: sinc_regs::aes_test_data_in_2.aes_test_data_in_2
`define SINC_REGS_AES_TEST_DATA_IN_2_AES_TEST_DATA_IN_2_MSB 31
`define SINC_REGS_AES_TEST_DATA_IN_2_AES_TEST_DATA_IN_2_LSB 0
`define SINC_REGS_AES_TEST_DATA_IN_2_AES_TEST_DATA_IN_2_WIDTH 32
`define SINC_REGS_AES_TEST_DATA_IN_2_AES_TEST_DATA_IN_2_RANGE 31:0
`define SINC_REGS_AES_TEST_DATA_IN_2_AES_TEST_DATA_IN_2_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_2_AES_TEST_DATA_IN_2_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_2_AES_TEST_DATA_IN_2_RESET 32'h00000000
`define SINC_REGS_AES_TEST_DATA_IN_2_AES_TEST_DATA_IN_2_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::aes_test_data_in_3
// Register template: sinc_regs::aes_test_data_in_3
`define SINC_REGS_AES_TEST_DATA_IN_3_OUTPUT_PORT_MSB 31
`define SINC_REGS_AES_TEST_DATA_IN_3_OUTPUT_PORT_LSB 0
`define SINC_REGS_AES_TEST_DATA_IN_3_OUTPUT_PORT_WIDTH 32
`define SINC_REGS_AES_TEST_DATA_IN_3_OUTPUT_PORT_RANGE 31:0
// Field member: sinc_regs::aes_test_data_in_3.aes_test_data_in_3
`define SINC_REGS_AES_TEST_DATA_IN_3_AES_TEST_DATA_IN_3_MSB 31
`define SINC_REGS_AES_TEST_DATA_IN_3_AES_TEST_DATA_IN_3_LSB 0
`define SINC_REGS_AES_TEST_DATA_IN_3_AES_TEST_DATA_IN_3_WIDTH 32
`define SINC_REGS_AES_TEST_DATA_IN_3_AES_TEST_DATA_IN_3_RANGE 31:0
`define SINC_REGS_AES_TEST_DATA_IN_3_AES_TEST_DATA_IN_3_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_3_AES_TEST_DATA_IN_3_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_IN_3_AES_TEST_DATA_IN_3_RESET 32'h00000000
`define SINC_REGS_AES_TEST_DATA_IN_3_AES_TEST_DATA_IN_3_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::aes_test_data_out_0
// Register template: sinc_regs::aes_test_data_out_0
// Field member: sinc_regs::aes_test_data_out_0.aes_test_data_out_0
`define SINC_REGS_AES_TEST_DATA_OUT_0_AES_TEST_DATA_OUT_0_MSB 31
`define SINC_REGS_AES_TEST_DATA_OUT_0_AES_TEST_DATA_OUT_0_LSB 0
`define SINC_REGS_AES_TEST_DATA_OUT_0_AES_TEST_DATA_OUT_0_WIDTH 32
`define SINC_REGS_AES_TEST_DATA_OUT_0_AES_TEST_DATA_OUT_0_RANGE 31:0
`define SINC_REGS_AES_TEST_DATA_OUT_0_AES_TEST_DATA_OUT_0_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_OUT_0_AES_TEST_DATA_OUT_0_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_DATA_OUT_0_AES_TEST_DATA_OUT_0_RESET 32'h00000000
`define SINC_REGS_AES_TEST_DATA_OUT_0_AES_TEST_DATA_OUT_0_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::aes_test_data_out_1
// Register template: sinc_regs::aes_test_data_out_1
// Field member: sinc_regs::aes_test_data_out_1.aes_test_data_out_1
`define SINC_REGS_AES_TEST_DATA_OUT_1_AES_TEST_DATA_OUT_1_MSB 31
`define SINC_REGS_AES_TEST_DATA_OUT_1_AES_TEST_DATA_OUT_1_LSB 0
`define SINC_REGS_AES_TEST_DATA_OUT_1_AES_TEST_DATA_OUT_1_WIDTH 32
`define SINC_REGS_AES_TEST_DATA_OUT_1_AES_TEST_DATA_OUT_1_RANGE 31:0
`define SINC_REGS_AES_TEST_DATA_OUT_1_AES_TEST_DATA_OUT_1_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_OUT_1_AES_TEST_DATA_OUT_1_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_DATA_OUT_1_AES_TEST_DATA_OUT_1_RESET 32'h00000000
`define SINC_REGS_AES_TEST_DATA_OUT_1_AES_TEST_DATA_OUT_1_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::aes_test_data_out_2
// Register template: sinc_regs::aes_test_data_out_2
// Field member: sinc_regs::aes_test_data_out_2.aes_test_data_out_2
`define SINC_REGS_AES_TEST_DATA_OUT_2_AES_TEST_DATA_OUT_2_MSB 31
`define SINC_REGS_AES_TEST_DATA_OUT_2_AES_TEST_DATA_OUT_2_LSB 0
`define SINC_REGS_AES_TEST_DATA_OUT_2_AES_TEST_DATA_OUT_2_WIDTH 32
`define SINC_REGS_AES_TEST_DATA_OUT_2_AES_TEST_DATA_OUT_2_RANGE 31:0
`define SINC_REGS_AES_TEST_DATA_OUT_2_AES_TEST_DATA_OUT_2_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_OUT_2_AES_TEST_DATA_OUT_2_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_DATA_OUT_2_AES_TEST_DATA_OUT_2_RESET 32'h00000000
`define SINC_REGS_AES_TEST_DATA_OUT_2_AES_TEST_DATA_OUT_2_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::aes_test_data_out_3
// Register template: sinc_regs::aes_test_data_out_3
// Field member: sinc_regs::aes_test_data_out_3.aes_test_data_out_3
`define SINC_REGS_AES_TEST_DATA_OUT_3_AES_TEST_DATA_OUT_3_MSB 31
`define SINC_REGS_AES_TEST_DATA_OUT_3_AES_TEST_DATA_OUT_3_LSB 0
`define SINC_REGS_AES_TEST_DATA_OUT_3_AES_TEST_DATA_OUT_3_WIDTH 32
`define SINC_REGS_AES_TEST_DATA_OUT_3_AES_TEST_DATA_OUT_3_RANGE 31:0
`define SINC_REGS_AES_TEST_DATA_OUT_3_AES_TEST_DATA_OUT_3_READ_ACCESS 1
`define SINC_REGS_AES_TEST_DATA_OUT_3_AES_TEST_DATA_OUT_3_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_DATA_OUT_3_AES_TEST_DATA_OUT_3_RESET 32'h00000000
`define SINC_REGS_AES_TEST_DATA_OUT_3_AES_TEST_DATA_OUT_3_FIELD_MASK 32'hffffffff

// Register type: sinc_regs::aes_test_ctrl
// Register template: sinc_regs::aes_test_ctrl
`define SINC_REGS_AES_TEST_CTRL_OUTPUT_PORT_MSB 17
`define SINC_REGS_AES_TEST_CTRL_OUTPUT_PORT_LSB 0
`define SINC_REGS_AES_TEST_CTRL_OUTPUT_PORT_WIDTH 18
`define SINC_REGS_AES_TEST_CTRL_OUTPUT_PORT_RANGE 17:0
// Field member: sinc_regs::aes_test_ctrl.data_out_ack
`define SINC_REGS_AES_TEST_CTRL_DATA_OUT_ACK_MSB 17
`define SINC_REGS_AES_TEST_CTRL_DATA_OUT_ACK_LSB 17
`define SINC_REGS_AES_TEST_CTRL_DATA_OUT_ACK_WIDTH 1
`define SINC_REGS_AES_TEST_CTRL_DATA_OUT_ACK_RANGE 17:17
`define SINC_REGS_AES_TEST_CTRL_DATA_OUT_ACK_READ_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_DATA_OUT_ACK_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_DATA_OUT_ACK_RESET 1'h0
`define SINC_REGS_AES_TEST_CTRL_DATA_OUT_ACK_FIELD_MASK 32'h00020000
// Field member: sinc_regs::aes_test_ctrl.data_in_aad_sel
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_AAD_SEL_MSB 16
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_AAD_SEL_LSB 16
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_AAD_SEL_WIDTH 1
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_AAD_SEL_RANGE 16:16
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_AAD_SEL_READ_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_AAD_SEL_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_AAD_SEL_RESET 1'h0
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_AAD_SEL_FIELD_MASK 32'h00010000
// Field member: sinc_regs::aes_test_ctrl.data_in_last
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_LAST_MSB 15
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_LAST_LSB 15
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_LAST_WIDTH 1
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_LAST_RANGE 15:15
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_LAST_READ_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_LAST_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_LAST_RESET 1'h0
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_LAST_FIELD_MASK 32'h00008000
// Field member: sinc_regs::aes_test_ctrl.data_in_byte_cnt
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_BYTE_CNT_MSB 14
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_BYTE_CNT_LSB 10
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_BYTE_CNT_WIDTH 5
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_BYTE_CNT_RANGE 14:10
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_BYTE_CNT_READ_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_BYTE_CNT_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_BYTE_CNT_RESET 5'h00
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_BYTE_CNT_FIELD_MASK 32'h00007c00
// Field member: sinc_regs::aes_test_ctrl.data_in_vld
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_VLD_MSB 9
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_VLD_LSB 9
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_VLD_WIDTH 1
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_VLD_RANGE 9:9
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_VLD_READ_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_VLD_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_VLD_RESET 1'h0
`define SINC_REGS_AES_TEST_CTRL_DATA_IN_VLD_FIELD_MASK 32'h00000200
// Field member: sinc_regs::aes_test_ctrl.cfg_key_iv_vld
`define SINC_REGS_AES_TEST_CTRL_CFG_KEY_IV_VLD_MSB 8
`define SINC_REGS_AES_TEST_CTRL_CFG_KEY_IV_VLD_LSB 8
`define SINC_REGS_AES_TEST_CTRL_CFG_KEY_IV_VLD_WIDTH 1
`define SINC_REGS_AES_TEST_CTRL_CFG_KEY_IV_VLD_RANGE 8:8
`define SINC_REGS_AES_TEST_CTRL_CFG_KEY_IV_VLD_READ_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_CFG_KEY_IV_VLD_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_CFG_KEY_IV_VLD_RESET 1'h0
`define SINC_REGS_AES_TEST_CTRL_CFG_KEY_IV_VLD_FIELD_MASK 32'h00000100
// Field member: sinc_regs::aes_test_ctrl.reuse_key
`define SINC_REGS_AES_TEST_CTRL_REUSE_KEY_MSB 7
`define SINC_REGS_AES_TEST_CTRL_REUSE_KEY_LSB 7
`define SINC_REGS_AES_TEST_CTRL_REUSE_KEY_WIDTH 1
`define SINC_REGS_AES_TEST_CTRL_REUSE_KEY_RANGE 7:7
`define SINC_REGS_AES_TEST_CTRL_REUSE_KEY_READ_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_REUSE_KEY_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_REUSE_KEY_RESET 1'h0
`define SINC_REGS_AES_TEST_CTRL_REUSE_KEY_FIELD_MASK 32'h00000080
// Field member: sinc_regs::aes_test_ctrl.key_len
`define SINC_REGS_AES_TEST_CTRL_KEY_LEN_MSB 6
`define SINC_REGS_AES_TEST_CTRL_KEY_LEN_LSB 5
`define SINC_REGS_AES_TEST_CTRL_KEY_LEN_WIDTH 2
`define SINC_REGS_AES_TEST_CTRL_KEY_LEN_RANGE 6:5
`define SINC_REGS_AES_TEST_CTRL_KEY_LEN_READ_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_KEY_LEN_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_KEY_LEN_RESET 2'h0
`define SINC_REGS_AES_TEST_CTRL_KEY_LEN_FIELD_MASK 32'h00000060
// Field member: sinc_regs::aes_test_ctrl.dir
`define SINC_REGS_AES_TEST_CTRL_DIR_MSB 4
`define SINC_REGS_AES_TEST_CTRL_DIR_LSB 4
`define SINC_REGS_AES_TEST_CTRL_DIR_WIDTH 1
`define SINC_REGS_AES_TEST_CTRL_DIR_RANGE 4:4
`define SINC_REGS_AES_TEST_CTRL_DIR_READ_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_DIR_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_DIR_RESET 1'h0
`define SINC_REGS_AES_TEST_CTRL_DIR_FIELD_MASK 32'h00000010
// Field member: sinc_regs::aes_test_ctrl.mode
`define SINC_REGS_AES_TEST_CTRL_MODE_MSB 3
`define SINC_REGS_AES_TEST_CTRL_MODE_LSB 0
`define SINC_REGS_AES_TEST_CTRL_MODE_WIDTH 4
`define SINC_REGS_AES_TEST_CTRL_MODE_RANGE 3:0
`define SINC_REGS_AES_TEST_CTRL_MODE_READ_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_MODE_WRITE_ACCESS 1
`define SINC_REGS_AES_TEST_CTRL_MODE_RESET 4'h0
`define SINC_REGS_AES_TEST_CTRL_MODE_FIELD_MASK 32'h0000000f

// Register type: sinc_regs::aes_test_status
// Register template: sinc_regs::aes_test_status
`define SINC_REGS_AES_TEST_STATUS_OUTPUT_PORT_MSB 3
`define SINC_REGS_AES_TEST_STATUS_OUTPUT_PORT_LSB 0
`define SINC_REGS_AES_TEST_STATUS_OUTPUT_PORT_WIDTH 4
`define SINC_REGS_AES_TEST_STATUS_OUTPUT_PORT_RANGE 3:0
// Field member: sinc_regs::aes_test_status.tag_out
`define SINC_REGS_AES_TEST_STATUS_TAG_OUT_MSB 3
`define SINC_REGS_AES_TEST_STATUS_TAG_OUT_LSB 3
`define SINC_REGS_AES_TEST_STATUS_TAG_OUT_WIDTH 1
`define SINC_REGS_AES_TEST_STATUS_TAG_OUT_RANGE 3:3
`define SINC_REGS_AES_TEST_STATUS_TAG_OUT_READ_ACCESS 1
`define SINC_REGS_AES_TEST_STATUS_TAG_OUT_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_STATUS_TAG_OUT_RESET 1'h0
`define SINC_REGS_AES_TEST_STATUS_TAG_OUT_FIELD_MASK 32'h00000008
// Field member: sinc_regs::aes_test_status.data_out_vld
`define SINC_REGS_AES_TEST_STATUS_DATA_OUT_VLD_MSB 2
`define SINC_REGS_AES_TEST_STATUS_DATA_OUT_VLD_LSB 2
`define SINC_REGS_AES_TEST_STATUS_DATA_OUT_VLD_WIDTH 1
`define SINC_REGS_AES_TEST_STATUS_DATA_OUT_VLD_RANGE 2:2
`define SINC_REGS_AES_TEST_STATUS_DATA_OUT_VLD_READ_ACCESS 1
`define SINC_REGS_AES_TEST_STATUS_DATA_OUT_VLD_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_STATUS_DATA_OUT_VLD_RESET 1'h0
`define SINC_REGS_AES_TEST_STATUS_DATA_OUT_VLD_FIELD_MASK 32'h00000004
// Field member: sinc_regs::aes_test_status.data_in_rdy
`define SINC_REGS_AES_TEST_STATUS_DATA_IN_RDY_MSB 1
`define SINC_REGS_AES_TEST_STATUS_DATA_IN_RDY_LSB 1
`define SINC_REGS_AES_TEST_STATUS_DATA_IN_RDY_WIDTH 1
`define SINC_REGS_AES_TEST_STATUS_DATA_IN_RDY_RANGE 1:1
`define SINC_REGS_AES_TEST_STATUS_DATA_IN_RDY_READ_ACCESS 1
`define SINC_REGS_AES_TEST_STATUS_DATA_IN_RDY_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_STATUS_DATA_IN_RDY_RESET 1'h0
`define SINC_REGS_AES_TEST_STATUS_DATA_IN_RDY_FIELD_MASK 32'h00000002
// Field member: sinc_regs::aes_test_status.cfg_key_iv_rdy
`define SINC_REGS_AES_TEST_STATUS_CFG_KEY_IV_RDY_MSB 0
`define SINC_REGS_AES_TEST_STATUS_CFG_KEY_IV_RDY_LSB 0
`define SINC_REGS_AES_TEST_STATUS_CFG_KEY_IV_RDY_WIDTH 1
`define SINC_REGS_AES_TEST_STATUS_CFG_KEY_IV_RDY_RANGE 0:0
`define SINC_REGS_AES_TEST_STATUS_CFG_KEY_IV_RDY_READ_ACCESS 1
`define SINC_REGS_AES_TEST_STATUS_CFG_KEY_IV_RDY_WRITE_ACCESS 0
`define SINC_REGS_AES_TEST_STATUS_CFG_KEY_IV_RDY_RESET 1'h0
`define SINC_REGS_AES_TEST_STATUS_CFG_KEY_IV_RDY_FIELD_MASK 32'h00000001

// Register type: sinc_regs::encr_block_status
// Register template: sinc_regs::encr_block_status
// Field member: sinc_regs::encr_block_status.num_of_blocks_encr
`define SINC_REGS_ENCR_BLOCK_STATUS_NUM_OF_BLOCKS_ENCR_MSB 11
`define SINC_REGS_ENCR_BLOCK_STATUS_NUM_OF_BLOCKS_ENCR_LSB 0
`define SINC_REGS_ENCR_BLOCK_STATUS_NUM_OF_BLOCKS_ENCR_WIDTH 12
`define SINC_REGS_ENCR_BLOCK_STATUS_NUM_OF_BLOCKS_ENCR_RANGE 11:0
`define SINC_REGS_ENCR_BLOCK_STATUS_NUM_OF_BLOCKS_ENCR_READ_ACCESS 1
`define SINC_REGS_ENCR_BLOCK_STATUS_NUM_OF_BLOCKS_ENCR_WRITE_ACCESS 0
`define SINC_REGS_ENCR_BLOCK_STATUS_NUM_OF_BLOCKS_ENCR_RESET 12'h000
`define SINC_REGS_ENCR_BLOCK_STATUS_NUM_OF_BLOCKS_ENCR_FIELD_MASK 32'h00000fff

`endif
